### ISSUE TITLE
Несколько функций

### ISSUE THREAD

**Issue by siteincity** [alexusmai/laravel-file-manager#1]
Отличный пакет!
1. Было бы неплохо добавить возможность указывать при загрузке сразу диск и папку 
file-manager/ckeditor?disk=site&path=image - как-то так
2. Запоминал последнюю открытую папку
3. Не разобрался как добавить его на кнопку, допустим, "добавить изображение", чтобы при выборе он закрывал окно и возвращал путь к выбранному изображению
4. Удаление файла, несколько избыточно в окне еще и галочкой подтверждать удаление, лишние клики, когда работаешь с наполнением сайта весь день, кажддый лишний клик существенно увеличивает усталость =)

**Comment by alexusmai** [comment]
Спасибо за отзыв. Насчет нового функционала - пока нет времени, и пока не решил буду продолжать  разработку данного пакета или нет, просто он оказался невостребованным(за 2 месяца 26 загрузок, из которых около половины мои). Но если продолжу учту предложения.

**Comment by siteincity** [comment]
Да он был бы востребован, просто его нет в гугле, его перебивает кривой на всю голову пакет laravel-filemanager с 50% от нужного функционала. Он вообще ничего не умеет. А ваш пакет умеет все что нужно, его можно только улучшать и продвигать. И, возможно, переделать чтобы не привязывался к VUE, я, например, не использую VUE. Мне не хватает знаний, но добавив совсем небольшие изменения, ваш будет топ (сам ставил почти все что есть, вы даже не представляете на сколько там все ужасно)

**Comment by alexusmai** [comment]
Вся frontend часть написана на Vue поэтому отказаться от него не выйдет. Я кстати для изучения Vue и начал писать этот пакет, советую попробовать разобраться с этим фреймворком, он не очень замудреный..
