### ISSUE TITLE
Key exists checking is missing

### ISSUE THREAD

**Issue by et-nik** [alexusmai/laravel-file-manager#10]
Here -- https://github.com/alexusmai/laravel-file-manager/blob/master/src/FileManager.php#L43

If disk not exist in config `filesystems.disks` but exist in `file-manager.diskList` we get error 'Undefined index'.

Maybe add key existence checking (array_key_exists)?

```php
// disk list
foreach (config('file-manager.diskList') as $disk) {
    if (array_key_exists($disk, config('filesystems.disks'))) {
        $config['disks'][$disk] = array_only(
            config('filesystems.disks')[$disk], ['driver']
        );
    }
}
```

**Comment by alexusmai** [comment]
Thank you, the key existence check has been added.
