### ISSUE TITLE
hide directory path

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/laravel-file-manager#100]
i use acl for each user, and work fine ... but have problem for display path of folder

do i can remove path of user folder  ?

in folder upload i created folder by user name . i need start path after folder name !!

vahid/
to
/

**Comment by alexusmai** [comment]
Hi, you can't do it..

If you are using ACL - you can hide folders of another users and auto select the folder what you needed (docs)[https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#you-can-set-default-disk-and-default-path], to use this function for different users you can use (Dynamic configuration)[https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#dynamic-configuration]

Or you can create discs for all users if there are not many..

**Comment by vahidalvandi** [comment]
i hide folder , i want to hide folder name for user

**Comment by alexusmai** [comment]
FM doesn't have functionality for it.
