### ISSUE TITLE
Hide Right Click Menu

### ISSUE THREAD

**Issue by anilone** [alexusmai/laravel-file-manager#101]
Can i hide right click menu, except for 'Download' and "Properties ?

![Right_click](https://user-images.githubusercontent.com/700857/70024063-49d73980-15bf-11ea-948d-d93910370be8.png)

**Comment by alexusmai** [comment]
Hi, no such functionality.

**Comment by anilone** [comment]
Thanks for the reply !

**Comment by Flowerskater** [comment]
````
window.oncontextmenu = function(ev) {document.querySelector('.fm-context-menu').remove()}
````

**Comment by muhfajarm** [comment]
> 

but can just remove download button?
