### ISSUE TITLE
Facybox 3 instead of window

### ISSUE THREAD

**Issue by Sepremex** [alexusmai/laravel-file-manager#102]
when using buttons or with any WYSIWYG (textarea), is there a way to open the FM window with [FancyBox](http://fancyapps.com) ?

**Comment by vahidalvandi** [comment]
this is few heavy weight

**Comment by Miesie** [comment]
Hi @Sepremex,

I tried the same, but with a bootstrap modal. Please see [this](https://github.com/alexusmai/laravel-file-manager/issues/112) issue for the way to open the RM window in something else then the browser window. 

I hope this will show the information you needed!

Greetings

**Comment by Sepremex** [comment]
@Miesie, thank you, 
Not what I want, not what I expected, but is something I can work with, I'm doing something similar as your project CMS, mine is a personal blog, at first I was thinking to use Joomla, or WP, but since I'm learning Laravel, why not doing it while learning...
Thank you.
