### ISSUE TITLE
I can't use in mobile and issues of Ckeditor

### ISSUE THREAD

**Issue by smbongtoi85** [alexusmai/laravel-file-manager#104]
A nice library!
But I have 2 question:
1- How to just allow admin see file image ( jpg, png, gif... ) in CKeditor, but still can see all file in file manager?
2- I can't use event "Double Click" to open folder in Fife Manager, because I think that, mobile have not event "double click". How to fix it?

Thanks for reading!

**Comment by smbongtoi85** [comment]
3 days passed, I did not receive any feedback. I looking forward to the feedback. Again, I love so much this package.

**Comment by alexusmai** [comment]
Hi, i have bad news for you...
1. FM doesn't have functions for it
2. I didn't do optimization for mobile devices

**Comment by smbongtoi85** [comment]
Haizzzzzzzzzzzzzzzz!
This package is so good and I will still use it for current project.
Hope that, In next version, issues will be solved.
Thanks for reply.
