### ISSUE TITLE
ERROR DefaultConfigRepository.php line 31

### ISSUE THREAD

**Issue by tok3** [alexusmai/laravel-file-manager#105]
Not Possible to update composer anymore,  I always getting the following error: 

`In DefaultConfigRepository.php line 31:
Parse error: syntax error, unexpected '?'                                              
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
`

This happens only on apache test and production server but not on my local system using artisan. 
The system is Debian 4.9.189-3+deb9u2, php cli version is PHP 7.2.25

Any idea what could it cause and how to fix it ?

**Comment by alexusmai** [comment]
Hi,
 
```
// line 31
public function getLeftDisk(): ?string
```

`?string` - should work in PHP 7.1.0 and higher - check your php and php modules
