### ISSUE TITLE
s3 file size reporting incorrectly in status bar

### ISSUE THREAD

**Issue by leaninonlife** [alexusmai/laravel-file-manager#106]
The status bar is reporting incorrect file size for directory

![image](https://user-images.githubusercontent.com/3332344/70945631-3d20ff80-201b-11ea-977b-1ef375acbdb8.png)

![image](https://user-images.githubusercontent.com/3332344/70945657-49a55800-201b-11ea-8c2b-1df941b4da8f.png)

**Comment by alexusmai** [comment]
Hi, thank you. 
I found a problem and it will be fixed in the new version.
