### ISSUE TITLE
new Disklist on controller

### ISSUE THREAD

**Issue by Djomobil** [alexusmai/laravel-file-manager#107]
Hello it's possible to declare a new disklist in controller ?

i've lot of sftp information, i would like to update the diskList from Config::set("file-manager.diskList", [$newDisk])

Thk

**Comment by alexusmai** [comment]
Hi,
"Config::set" will not work

You can use (Dynamic configuration)[https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#dynamic-configuration]

**Comment by Djomobil** [comment]
Yes i've see but i need to set config/filesystems.php with all information about all SFTP connexion.

But i've 1000 sftp option and all day 5or 7 more. so, if i need to modify config file all day ...

**Comment by alexusmai** [comment]
You can try to call Config::set in the "getDiskList" method, this method is called for each FM request (RequestValidator). But I didn't check it..

```
public function getDiskList(): array
    {
        \Config::set('filesystems', [
            'disks' => [

                'images' => [
                    'driver' => 'local',
                    'root' => public_path('images'),
                ],

                'files' => [
                    'driver' => 'local',
                    'root' => public_path('files'),
                ],
            ],
        ]);

        return ['images', 'files'];
    }
```

**Comment by Djomobil** [comment]
i will try. thk

**Comment by Djomobil** [comment]
i've try : this 

`
public function __construct(Website $website, array $infoApi)
    {
        $this->website = $website;
        $this->infoApi = $infoApi;
    }

/**
     * Get disk list
     *
     * ['public', 'local', 's3']
     *
     * @return array
     */
    public function getDiskList(): array
    {
        $domain = str_replace('.', '_', $this->website->domain);
        \Config::set(
            'filesystems.disks',
            array_merge(
                \Config::get('filesystems.disks'),
                [
                    "$domain" => [
                        'driver'     => 'sftp',
                        'host'       => $this->infoApi['host'],
                        'username'   => $this->infoApi['ftp_login'],
                        'privateKey' => env('PATH_ID_RSA'),
                        'port'       => 2121,
                        'root'       => 'htdocs',
                    ],
                ]
            )
        );
        $return = [];
        foreach (\Config::get('filesystems.disks') as $disk => $arr) {
            $return[] = $disk;
        }
        return [$domain];
    }`

and in my controller :
`
new FilemanagerRepository($website, $info_from_api);
`
But load the first config.

**Comment by alexusmai** [comment]
Create new config repository:

```
<?php

namespace App;

/**
 * Class MyConfigRepositoryName
 *
 * @package Alexusmai\LaravelFileManager\Services\ConfigService
 */
class MyConfigRepositoryName implements ConfigRepository
{
    /**
     * Get disk list
     *
     * ['public', 'local', 's3']
     *
     * @return array
     */
    public function getDiskList(): array
    {
        return config('file-manager.diskList');
    }

// you can copy all methods from DefaultConfigRepository
}
```
- [DefaultConfigRepository](https://github.com/alexusmai/laravel-file-manager/blob/master/src/Services/ConfigService/DefaultConfigRepository.php)

And you need to edit the file manager settings file (config/file-manager.php)

```
'configRepository' => DefaultConfigRepository::class,
// TO
 'configRepository' => \App\MyConfigRepositoryName::class, // set your name

```

You don't need to call this class from your controller!

**Comment by Djomobil** [comment]
In configRepository can i get input in request for get Disk or something like that

**Comment by alexusmai** [comment]
```
request()->input('disk');
```

**Comment by Djomobil** [comment]
Hello,

I've try this : 
```php
use Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository;
use App\User;
use App\Website;

class FilemanagerRepository implements ConfigRepository
{

    /**
     * Get disk list
     *
     * ['public', 'local', 's3']
     *
     * @return array
     */
    public function getDiskList(): array
    {
        $user = User::find(\Auth::id());
        if (!$user) {
            return [];
        } elseif ($user && $user->role == 3) {
            return ['copylaunch'];
        }

        foreach (Website::where('domain', request()->input('leftDisk'))->get() as $website) {
            if ($website->hosting) {
                if ($website->hosting->api) {
                    $infoApi = $website->hosting->api->getInfoWebSite($website);
                    $domain  = str_replace('.', '_', $website->domain);
                    if (!empty($infoApi) && !isset($infoApi['Info'])) {
                        \Config::set(
                            'filesystems.disks',
                            array_merge(
                                \Config::get('filesystems.disks'),
                                [
                                    "$domain" => [
                                        'driver'     => 'sftp',
                                        'host'       => $infoApi['host'],
                                        'username'   => $infoApi['ftp_login'],
                                        'privateKey' => env('PATH_ID_RSA'),
                                        'port'       => 22,
                                        'root'       => 'www',
                                    ],
                                ]
                            )
                        );
                    }
                }
            }
        }
        $return = [];
        foreach (\Config::get('filesystems.disks') as $disk => $arr) {
            $return[] = $disk;
        }
        return $return;
    }
```

But not working when i dump my config in blade : 
```php
@dump(\Config::get('filesystems.disks'))
```

Nothing. u have an idea ?

**Comment by Djomobil** [comment]
Ok i've interrensting the problem:

the function GetDiskList is called without argument, 

![Capture d’écran 2019-12-23 à 15 47 15](https://user-images.githubusercontent.com/11764599/71364201-c6947c80-259b-11ea-933f-867eeb47db99.png)

So i can't load new disk dynamically... i need to do before maybe.

**Comment by alexusmai** [comment]
You can use session:

Page1 -> FileManager(disk1, disk2)
Page2 -> FM(disk3)

Route(/page1) ---> (PageController  ---> session('key' => 'page1') ---> view template with FM)

```
public function getDiskList(): array
{
    $key = session('key');

    // generate settings list and set

}

```

**Comment by HIDAN122** [comment]
Здравствуйте,а есть возможность денамически менять значения для дисков?
