### ISSUE TITLE
Url public S3 bucket

### ISSUE THREAD

**Issue by Djomobil** [alexusmai/laravel-file-manager#108]
Hello, i've integrate your package in ckeditor 4.

I can upload file perfectly, but when i select my image: i've the private url.
exemple : 
i've :  https://s3.eu-west-3.amazonaws.com/company/mybucket/myimage.png
i would like : https://**mybucket**.s3.eu-west-3.amazonaws.com/**mybucket**/myimagepng

i need to config something ?
Thank for helping me

**Comment by alexusmai** [comment]
Hi, you can try to set AWS_URL in .env file

```
AWS_URL=https://bucket-name.s3.region-name.amazonaws.com
```

**Comment by Djomobil** [comment]
I've already 
`
AWS_URL='https://s3.eu-west-3.amazonaws.com/company
`

But not public : 
`
https://mybucket.s3.eu-west-3.amazonaws.com/mybucket/myimagepng
`

**Comment by Djomobil** [comment]
i do this: 

fm.$store.commit('fm/setFileCallBack', function(fileUrl) {
      /**
       * Refacto for public url
       * @type {string}
       */
      let host = new URL(fileUrl).hostname;
      let url  = fileUrl.split( "{{env('AWS_URL')}}") ;
      fileUrl = 'https://bucketname.' + host + url[1];

      const funcNum = getUrlParam('CKEditorFuncNum');
      window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl);
      window.close();
    });
