### ISSUE TITLE
Str::slug() for slug file name

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/laravel-file-manager#110]
what is best way to laravel str_slug in file name ?

**Comment by alexusmai** [comment]
I don't understand what do you need to do..

**Comment by vahidalvandi** [comment]
user upload file like this

عکس نمونه.jpg

i want a way to send name to slug function before save file to convert to

aks-nemone.jpg

**Comment by alexusmai** [comment]
Hi, no such function. You'll need to edit the source code.. (laravel package and maybe vue)

**Comment by VincentVanWijk** [comment]
maybe use the FilesUploaded Event?
I use simple str_replace for example but you can also use a slugging service.
maybe something like this?:

```
class UploadImageListener
{
    /**
     * Handle the event.
     *
     * @param  FilesUploaded  $event
     * @return void
     */
    public function handle($event)
    {
        foreach ($event->files() as $file) {
            $path = $file['path'];
            $newPath = str_replace(' ', '_', $path);
            if ($path != $newPath) {
                \Storage::move($path, $newPath);
            }
        }
    }
}
```

**Comment by vahidalvandi** [comment]
Str::slug() automaticaly convert persian charactor to english

**Comment by VincentVanWijk** [comment]
@vahidalvandi Does it work when you use` Str::slug` instead of `str_replace`?

**Comment by vahidalvandi** [comment]
> @vahidalvandi Does it work when you use` Str::slug` instead of `str_replace`?

thank you i need test it ...

**Comment by vahidalvandi** [comment]
when get image from url if url containn space return error "image source not readable"

```
                $photo = Image::make(Storage::disk($event->disk())->url($value['path']))->widen(1800, function ($constraint) {
                    $constraint->upsize();
                })->encode($value['extension'], 95);
```

**Comment by vahidalvandi** [comment]
i solve this by change vendor symfony http file

vendor/symfony/http-foundation/File/UploadedFile.php

line 88

i chnage this
```

  public function getClientOriginalName()
    {
        return $this->originalName;
    }
```
to this
```
    public function getClientOriginalName()
    {

        $ext =  $this->getClientOriginalExtension() ;
        $filename = \Str::slug(pathinfo($this->originalName, PATHINFO_FILENAME));

        return $filename.'.'.$ext;
    }
```

how i can override getClientOriginalName() in my laravel app ??

**Comment by vahidalvandi** [comment]
simple way @alexusmai  plz add config for UUID instance original filename

**Comment by vahidalvandi** [comment]
simple way @alexusmai  plz add config for UUID instance original filename

**Comment by vahidalvandi** [comment]
i solve this problem with pull request https://github.com/alexusmai/laravel-file-manager/pull/133
