### ISSUE TITLE
Use file-manager in a modal

### ISSUE THREAD

**Issue by Miesie** [alexusmai/laravel-file-manager#112]
Hi,

First of all, this is a very good file-manager for laravel. Good job!

I am working on a simple CMS in laravel for educational purposes. In the create/edit view the user have the functionality to add an image or file with your file-manager.

In your documentation I can open the file-manager standalone with the `window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800')` that opens a new browser window.

Is it also possible to use the same functionality within a bootstrap modal? When I put the `<div id="fm"></div>` in a modal it wont let me select a file, but only create/edit files.

I hope you can help me or give me some tips for this problem.

Thank you and happy holidays,

Michel

**Comment by VIPER-VLAD** [comment]
I'm thinking it is that you need:
[Click](https://codepen.io/VIPER-VLAD/pen/zYxmOEj)

**Comment by Miesie** [comment]
Hi @VIPER-VLAD,

Thank you for your reply. It is possible to open the file-manager in a modal. But I am looking for the same funtionality to select a file and NOT create/edit files. 

So what I want to accomplish is to open the file-manager in a modal, select a file and the modal will close. 

Greetings

**Comment by VIPER-VLAD** [comment]
@Miesie 

Instead of "console.log ()" you write your code.
For example, if you need to close modal and you use Bootstrap then you write.
``` javascript
fm.$store.commit('fm/setFileCallBack', function(fileUrl) {
    $('#file-manager-modal').modal('hide');
});
```
"fm/setFileCallBack" Allows you to override the action that will occur after a file is selected in the file manager.
In my example, after selecting the file, I call console.log, but you can write what you need.

``` javascript
fm.$store.commit('fm/setFileCallBack', function(fileUrl) {
    // action after file select is here
});
```

P.S.
Your "fm/setFileCallBack" override will should to add after "file-manager.js" include. Otherwise it will not work.

**Comment by Miesie** [comment]
@VIPER-VLAD 

It works!


`            fm.$store.commit('fm/setFileCallBack', function(fileUrl) {
                    document.getElementById('image-path').value = fileUrl;
                    document.getElementById('header-img').src = $('#image-path').val();
                $('#fmModal').modal('hide');
            });`

Thanks you very much for helping me! 

Greetings

**Comment by maksakoviliya** [comment]
Sorry, if i want to make modal with vue in what place i need to write fm.$store.commit...
