### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by iainheng** [alexusmai/laravel-file-manager#113]
Hi. Thanks for the great package. Can we change the date format from current mm/dd/yyyy to dd/mm/yyyy or yyyy/mm/dd?

**Comment by alexusmai** [comment]
Hi,
I added a fix in the new version. Now the date format is formed using the locale - [info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)
