### ISSUE TITLE
How can you use Standalone button in vue js?

### ISSUE THREAD

**Issue by ThisIsntMyId** [alexusmai/laravel-file-manager#115]
Somehow I managed to use this in my laravel vue js app and it works like charm. Now my question is how can you use Standalone button feature in vue.

**Comment by maksakoviliya** [comment]
Did you found the answer?

**Comment by ThisIsntMyId** [comment]
There isn't any. What I have done is use the store to get the selections.

**Comment by maksakoviliya** [comment]
> There isn't any. What I have done is use the store to get the selections.

https://github.com/alexusmai/vue-laravel-file-manager/issues/51#issuecomment-582551687
