### ISSUE TITLE
no preview of images in application div with grid view , works in wsywig integration and standalone button

### ISSUE THREAD

**Issue by VincentVanWijk** [alexusmai/laravel-file-manager#116]
Hi,
I have created a div in my application like so:

```
<div style="height: 600px;">
    <div id="fm"></div>
</div>
```

it shows the file manager, but when i switch to grid view, no previews are shown:

![image](https://user-images.githubusercontent.com/10919865/71730361-38917f00-2e42-11ea-8100-ace3f0d847c9.png)

However, i also integrated the filemanager in CKEditor and the standalone button, 
here it does work:

![image](https://user-images.githubusercontent.com/10919865/71730398-519a3000-2e42-11ea-88e5-ea75c8290544.png)

Do you have any idea what's causing this and how I can fix this? it seems to work in the demo.

Thanks in advance,
Vincent van Wijk

**Comment by alexusmai** [comment]
Hi, I can't repeat this problem, it's working for me.

Go to the network tab in your browser, select <Img> tab and reload page.

![fm-images](https://user-images.githubusercontent.com/7473505/72204060-f9d47800-3484-11ea-9aca-e491fdb43839.png)

Compare the urls of images (where the FM does work and where he doesn't work).

**Comment by VincentVanWijk** [comment]
Hi, thanks for replying,
I checked the network tab like you said, these are the results:

![image](https://user-images.githubusercontent.com/10919865/72256212-ea7e3780-3608-11ea-95f3-3a92b1831bfb.png)

looks like the request are simply not being made in the normal div version, no extra errors or exceptions that i can see

**Comment by VincentVanWijk** [comment]
double click to show preview works fine everywhere by the way

**Comment by VincentVanWijk** [comment]
i fixed the issue, although im not really sure why/how it happened.

While debugging i noticed that the the crop icon was not working (all the other were working fine):
![image](https://user-images.githubusercontent.com/10919865/72258340-16e88280-360e-11ea-8591-4cdaa0f5ba3e.png)

the crop icon DID work in the standalone and CKeditor implementations.

After updating my fontawesome to the latest version, the crop icon works again in the div implementation, and so the the image previews!
So somehow FontAweSome had something to do with it..

Thanks again for taking the time to reply,

Vincent
