### ISSUE TITLE
javascript - use function other than fmSetLink

### ISSUE THREAD

**Issue by Fredericld** [alexusmai/laravel-file-manager#118]
Hi

The default function updates the field name which is fine, but in some instances I want to display the thumbnail of the image selected, and in other instance I need to update other elements in the page. 

// default function
  function fmSetLink($url) {
    document.getElementById(inputId).value = $url;
  }

is it possible to call a function other than fmSetLink once a file has been selected?

In some instance I might want to do 

// set file link for uploader 
	function fmSetLink($url) {
	  document.getElementById(inputId).value = $url;
	  document.getElementById(inputId+"_thumb").src = "/"+$url;
	}

and sometimes add more code to the function

**Comment by Miesie** [comment]
Hi @Fredericld,

If you want to show a thumbnail of the image you can use the following.

```
// set file link for uploader
function fmSetLink($url) {

// This is an input element
document.getElementById(inputId).value = $url;

// This is an img element 
document.getElementById(imgId").src = $('#inputId').val();
}
```

I hope this will solve your problem!

Let me know.
