### ISSUE TITLE
How to use the aclRule array and change pemission with respect to user in runtime?

### ISSUE THREAD

**Issue by Ahmadzia307** [alexusmai/laravel-file-manager#12]
->file-manager file as follow:
<?php

return [
    'diskList'  => ['public'],
    'middleware' => ['web','fm-acl'],
    'acl' => true,
    'aclHideFromFM' => true,
    'aclStrategy'   => 'blacklist',
    'aclRepository' => Alexusmai\LaravelFileManager\ACLService\ConfigACLRepository::class,
    'aclRules'      => [
        1 => [
            ['disk' => 'public', 'path' => 'files/*', 'access' => 2],  
        ],
    ],
];
<br>
As I am setting the acl mode to true and  using acl rule.<br>
my view code is in the picture.<br>
![screenshot from 2019-02-08 12-10-35](https://user-images.githubusercontent.com/24617277/52477655-9d911600-2b9a-11e9-8caf-853dcb88c976.png)
<br>
but when I run my application and check the file manager. The directory it shows is different then, what is set in the aclRule array, as shown below<br>
![screenshot from 2019-02-08 12-25-55](https://user-images.githubusercontent.com/24617277/52478256-b4386c80-2b9c-11e9-81ca-0e757787e23e.png)

**Comment by alexusmai** [comment]
You probably did not configure everything as necessary. ACL is needed only to restrict user access to files and folders. And the main directory that will be displayed is set in the disk settings. See Laravel docs - https://laravel.com/docs/5.6/filesystem , in /config/filesystems.php set your disks, and then add disks what you want to FM config (/config/file-manager.php)

```
// Example
/**
     * list of disk names that you want to use
     * (from config/filesystems)
     */
    'diskList'  => ['images', 'docs', 'template', 'sftp', 'yandex'],

**Comment by Ahmadzia307** [comment]
Thank you for replying. One more thing, how I can use aclRule array in the laravel. Can you add some example in the documentation that would be very helpful?
So far, I am able to use the file manager with disklist =>['local']. Just I wasn't able to apply the aclRule array on the directory.

**Comment by alexusmai** [comment]
Example:

I have disk 'images' in /config/filesystems.php for folder /public/images
```
'disks' => [

        'images' => [
            'driver' => 'local',
            'root'   => public_path('images'),
            'url'    => '/images/',
        ],
]
```

This disk contain:

``` 
/
|-- nature
|-- cars
|-- icons
|-- image1.jpg
|-- image2.jpg
|-- avatar.png
```

I add this disk to file-manager config file

```
'diskList'  => ['images'],

'aclStrategy'   => 'blacklist',

// now it's a black list
'aclRules'      => [
       // null - for not authenticated users
        null => [
            ['disk' => 'images', 'path' => 'nature', 'access' => 0],    // guest don't have access for this folder
            ['disk' => 'images', 'path' => 'icons', 'access' => 1],    // only read - guest can't change folder - rename, delete
            ['disk' => 'images', 'path' => 'icons/*', 'access' => 1],     // only read all files and foders in this folder
            ['disk' => 'images', 'path' => 'image*.jpg', 'access' => 0], // can't read and write (preview, rename, delete..)
            ['disk' => 'images', 'path' => 'avatar.png', 'access' => 1],     // only read (view)

        ],
        // for user with ID = 1
        1 => [
            ['disk' => 'images', 'path' => 'cars', 'access' => 0],    // don't have access
            ['disk' => 'public', 'path' => 'image*.jpg', 'access' => 1],    // only read (view)
        ],
    ],
```

**Comment by Ahmadzia307** [comment]
Thanks alot. I just tried it  and it worked. 
In case of DB , Can I make my own class of the Dbrespository with two functions getID() and getRules?
Can you give me some idea how I can do it? 
Right now, it is in vendor and with User table. Also,I want to change the table with my own table.

**Comment by alexusmai** [comment]
Yes, you can create your own class, for example in the folder /app/HTTP

```
<?php

namespace App\Http;

use Alexusmai\LaravelFileManager\ACLService\ACLRepository;

class MyACLRepository implements ACLRepository
{
    /**
     * Get user ID
     *
     * @return mixed
     */
    public function getUserID()
    {
        return \Auth::id();
    }

    /**
     * Get ACL rules list for user
     *
     * @return array
     */
    public function getRules(): array
    {
        return \DB::table('acl_rules')
            ->where('user_id', $this->getUserID())
            ->get(['disk', 'path', 'access'])
            ->map(function ($item) {
                return get_object_vars($item);
            })
            ->all();
    }
}
```

in /config/file-manager change:

```
    'aclRepository' => \App\Http\MyACLRepository::class,
```

> Warning the getRules() method must return an array, not a object !!! see my example!

**Comment by Ahmadzia307** [comment]
Hi alex,
I am having a problem using acl rules with "whitelist".  My Aclrule is below:
I have folders
---files
-1
-2
-img

'aclStrategy'   => 'whitelist',
aclRules'      => [
        null => [
            ['disk' => 'local', 'path' => 'img', 'access' => 2],
            ['disk' => 'local', 'path' => '1', 'access' => 0],
                  ],
]`

Then when I run this, I got the error, Acess Denied.
![screenshot from 2019-02-11 07-48-50](https://user-images.githubusercontent.com/24617277/52550796-88ea9300-2dd1-11e9-8123-820a5b95a0c5.png)

**Comment by Ahmadzia307** [comment]
In case of blacklist, It is working.

![screenshot from 2019-02-11 07-50-44](https://user-images.githubusercontent.com/24617277/52550852-d6ff9680-2dd1-11e9-8130-9a0deaf81775.png)

**Comment by alexusmai** [comment]
> whitelist - Deny everything, that not allowed by the ACL rules list.

Root folder too!!!

Add new rule:

```
['disk' => 'local', 'path' => '/', 'access' => 2],

OR

['disk' => 'local', 'path' => '/', 'access' => 1],
```

**Comment by Ahmadzia307** [comment]
Thank you. It is working.
