### ISSUE TITLE
please add event when file manager is before opening

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/laravel-file-manager#122]
i need set default root to a directory it not exists i need event to create this folder before run file manager

**Comment by alexusmai** [comment]
### BeforeInitialization

> Alexusmai\LaravelFileManager\Events\BeforeInitialization

Example:

```php
\Event::listen('Alexusmai\LaravelFileManager\Events\BeforeInitialization',
    function ($event) {
        
    }
);
```
