### ISSUE TITLE
Change disk base path to user folder 

### ISSUE THREAD

**Issue by karol-piekarski** [alexusmai/laravel-file-manager#126]
How i can change disk base path to user folder?

**Comment by alexusmai** [comment]
Hi, disks settings you can find in this file config/filesysytems.php

Or maybe you meant this - [dynamic configuration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#dynamic-configuration)

**Comment by karol-piekarski** [comment]
Hi, 
I mean the ability to dynamically broadcast the base path for a particular user, ex:
`'app/public/' . auth()->user()->id` and the user only has access to his folder and cannot see others on the disk. You know what I mean?

**Comment by alexusmai** [comment]
Did you read this [doc](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md) ?
There you can find examples.
