### ISSUE TITLE
Why i dont see my images?

### ISSUE THREAD

**Issue by apokall** [alexusmai/laravel-file-manager#130]
Hello!
FileManager work good, but i dont see my images.
php 7.3 
apache
laravel 5.7
I installed everything that is needed for the package, circumvented topics about pictures, also installed the following:
GD Library or Imagick for intervention/image
requires intervention/image and intervention/imagecache
What else can you try? I can not understand what is the reason :(

**file-manager.php**
`
return [

    /**
     * list of disk names that you want to use
     * (from config/filesystems)
     */
    'diskList'  => ['public', 'images', 'sounds'],

    /**
     * Default disk for left manager
     * null - auto select the first disk in the disk list
     */
    'leftDisk'  => 'public',

    /**
     * Default disk for right manager
     * null - auto select the first disk in the disk list
     */
    'rightDisk' => null,

    /**
     * Default path for left manager
     * null - root directory
     */
    'leftPath'  => null,

    /**
     * Default path for right manager
     * null - root directory
     */
    'rightPath' => null,

    /**
     * Image cache ( Intervention Image Cache )
     * set null, 0 - if you don't need cache (default)
     * if you want use cache - set the number of minutes for which the value should be cached
     */
    'cache' => null,

    /**
     * File manager modules configuration
     * 1 - only one file manager window
     * 2 - one file manager window with directories tree module
     * 3 - two file manager windows
     */
    'windowsConfig' => 2,

    /***************************************************************************
     * Middleware
     * Add your middleware name to array -> ['web', 'auth', 'admin']
     * !!!! RESTRICT ACCESS FOR NON ADMIN USERS !!!!
     *
     * !!! For using ACL - add 'fm-acl' to array !!! ['web', 'fm-acl']
     */
    'middleware' => ['web'],

    /***************************************************************************
     * ACL mechanism ON/OFF
     *
     * default - false(OFF)
     */
    'acl' => false,

    /**
     * Hide files and folders from file-manager if user doesn't have access
     * ACL access level = 0
     */
    'aclHideFromFM' => true,

    /**
     * ACL strategy
     *
     * blacklist - Allow everything(access - 2 - r/w) that is not forbidden by the ACL rules list
     *
     * whitelist - Deny anything(access - 0 - deny), that not allowed by the ACL rules list
     */
    'aclStrategy'   => 'blacklist',

    /**
     * ACL rules repository
     *
     * default - config file(ConfigACLRepository)
     */
    'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\ConfigACLRepository::class,
    //'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\DBACLRepository::class,

    /**
     * ACL rules list - used for default repository
     *
     * 1 it's user ID
     * null - for not authenticated user
     *
     * 'disk' => 'disk-name'
     *
     * 'path' => 'folder-name'
     * 'path' => 'folder1*' - select folder1, folder12, folder1/sub-folder, ...
     * 'path' => 'folder2/*' - select folder2/sub-folder,... but not select folder2 !!!
     * 'path' => 'folder-name/file-name.jpg'
     * 'path' => 'folder-name/*.jpg'
     *
     * * - wildcard
     *
     * access: 0 - deny, 1 - read, 2 - read/write
     */
    'aclRules'      => [
        null => [
            //['disk' => 'public', 'path' => '/', 'access' => 2],
        ],
        1 => [
            //['disk' => 'public', 'path' => 'images/arch*.jpg', 'access' => 2],
            //['disk' => 'public', 'path' => 'files/*', 'access' => 1],
        ],
    ],

    /**
     * ACL Rules cache
     *
     * null or value in minutes
     */
    'aclRulesCache' => null,
];
`
**fylesystems.php**
![image](https://user-images.githubusercontent.com/12546313/74611156-02624300-5102-11ea-8354-0691a957b281.png)
**images:**
![image](https://user-images.githubusercontent.com/12546313/74611146-f9717180-5101-11ea-9e3e-93181374ddcb.png)
**Image url:**
http://some-site.loc/file-manager/preview?disk=public&path=augur-series-countdown-daily.png&v=1574092124

**Comment by alexusmai** [comment]
Hi,
What do you see in the browser console (network tab)? Did images upload success? code 200 or 404 ?
The Images url's should be like this - https://site.ru/file-manager/thumbnails?disk=.....&path=...
if you set this url in to the browser you should be see this image preview..

I think you have problems with image library(GD or Imagick) or maybe with server settings, to check it try to create thumbnail

```
function thumbnail()
{
    $thumbnail = Image::make(Storage::disk(_disk_name_)->get(_file-path_))->fit(80);
    return $thumbnail->response();
}
```

**Comment by apokall** [comment]
@alexusmai 
"What do you see in the browser console (network tab)? Did images upload success? code 200 or 404 ?"
- Status: 200
- Url: `http://someSite.loc/file-manager/thumbnails?disk=public&path=evening_ticket.png&v=1574092124`
![image](https://user-images.githubusercontent.com/12546313/74739374-5b94b880-5261-11ea-962f-edf4984fe0c6.png)
- Caption in the picture:
Image from http://someSite.loc/file-manager/thumbnails?disk=public&path=3_3.png&v=1574092124
I did what you said.
In my local,test,prod server already installed newest version of GD and Imagick.
```
<?php

namespace App\Http\Controllers\Html;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class TestController extends Controller
{
    public function test()
    {
        $thumbnail = Image::make(Storage::disk('public')->get('map.jpg'))->fit(80);
        return $thumbnail->response();
    }
}
```
- Status: 200
![image](https://user-images.githubusercontent.com/12546313/74739435-7a934a80-5261-11ea-8561-f1cf50af60cc.png)
- Caption in the picture:
Image from http://someSite.loc/test

**Comment by alexusmai** [comment]
As I can see, you got the answer, but the image is corrupted ... that means the thumbnail was not generated.
I don't know why is it happen.

Go to the [intervention/image](http://image.intervention.io/) site. Try to use another examples for testing.
Try to reinstall the FM (inervention/image and cache should be loaded automaticly as dependencies)
Check folder and file permissions.
