### ISSUE TITLE
How to integrate in vue component?

### ISSUE THREAD

**Issue by salamat1307** [alexusmai/laravel-file-manager#132]
How to integrate in vue component with tinymce/tinymce-vue package?

**Comment by maksakoviliya** [comment]
And it is intresting for me)

**Comment by alexusmai** [comment]
Examples for TinyMce4 and 5, how to connect - [link](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md#tinymce-4), [link2](https://github.com/alexusmai/laravel-file-manager/blob/master/examples/wysiwyg/tinymce.blade.php) but they relate to the regular version, not Vue.
How to use vue version I don't know, you'll need to ask this information in them repository..
