### ISSUE TITLE
/file-manager/initialize path

### ISSUE THREAD

**Issue by kdwight** [alexusmai/laravel-file-manager#136]
the website is on shared hosting and needs an extra URI after the main URL.

how to prepend an uri to the path so I won't get a 404 error with `/file-manager/initialize` path

**Comment by alexusmai** [comment]
Hi,

You'll need to compile your frontend with baseUrl - [vue-laravel-file-manager](https://github.com/alexusmai/vue-laravel-file-manager)

```
// settings object structure
settings: {
    baseUrl: 'http://test.loc/file-manager/',   // overwrite base url Axios
},
...
```

**Comment by assoft** [comment]
> the website is on shared hosting and needs an extra URI after the main URL.
> 
> how to prepend an uri to the path so I won't get a 404 error with `/file-manager/initialize` path

1. Open: public/vendor/file-manager/js/filemanager.js
2. Find `initAxiosSettings` method (maybe you can consider unminify)
3. Go `else block``
4. Replace this url:
```javascript
if (!e.baseUrl) {
    // ...
} else {
  var t = ""
    .concat(window.location.protocol, "//")
    .concat(window.location.hostname);
  window.location.port.length
    ? (t += ":".concat(window.location.port, "/site/file-manager/"))
    : (t += "/site/file-manager/"),
    (e.baseUrl = t);
}
```
