### ISSUE TITLE
Настройка

### ISSUE THREAD

**Issue by AliaksandrHaurylenka** [alexusmai/laravel-file-manager#14]
Привет!
При добавлении пользователя, который может лишь добавлять статьи, в файловую структуру добавляется папка с его именем для добавления изображений. Подскажи пожалуйста как разрешить пользователю вносить изменения лишь в своей папке?
Попробовал так:
`array('disk' => 'Пользователи', 'path' => '/news/'.Auth::user()->name, 'access' => 2)`
но получаю ошибку **A facade root has not been set**
Спасибо.

**Comment by alexusmai** [comment]
Привет.  Набросал пример:

- нужно создать новый репозиторий для ACL правил, например в папке /app/Http

```php
<?php

namespace App\Http;

use Alexusmai\LaravelFileManager\ACLService\ACLRepository;

class UsersACLRepository implements ACLRepository
{
    /**
     * Get user ID
     *
     * @return mixed
     */
    public function getUserID()
    {
        return \Auth::id();
    }

    /**
     * Get ACL rules list for user
     *
     * @return array
     */
    public function getRules(): array
    {
        return [
            ['disk' => 'disk-name', 'path' => '/', 'access' => 1],     // main folder - read
            ['disk' => 'disk-name', 'path' => 'news', 'access' => 1],  // only read
            ['disk' => 'disk-name', 'path' => 'news/'. \Auth::user()->name, 'access' => 1],        // only read
            ['disk' => 'disk-name', 'path' => 'news/'. \Auth::user()->name .'/*', 'access' => 2],  // read and write
        ];
    }
}
```
- disk-name - нужно заменить на свой,

- теперь в конфиг файле файлового менеджера изменим репозиторий на новый, а aclStrategy установим в whitelist - запретим все, что не разрешено правилами. Также можно скрыть папки и файлы к которым нет доступа.

```
/**
     * Hide files and folders from file-manager if user doesn't have access
     * ACL access level = 0
     */
    'aclHideFromFM' => true,

/**
     * ACL strategy
     *
     * blacklist - Allow everything(access - 2 - r/w) that is not forbidden by the ACL rules list
     *
     * whitelist - Deny anything(access - 0 - deny), that not allowed by the ACL rules list
     */
    'aclStrategy'   => 'whitelist',

/**
     * ACL rules repository
     *
     * default - config file(ConfigACLRepository)
     */
    'aclRepository' => \App\Http\UsersACLRepository::class,
```

Теперь в своей папке пользователь может создавать, удалять, и т.п. файлы и папки, а вот папки выше он изменить или удалить не сможет.

**Comment by AliaksandrHaurylenka** [comment]
Привет!
Спасибо большое. Все отлично работает.


>Четверг, 21 февраля 2019, 8:45 +03:00 от Alex <notifications@github.com>:
>
>Closed  #14 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
С уважением,
Александр Гавриленко
