### ISSUE TITLE
File type filter?

### ISSUE THREAD

**Issue by paulbacks** [alexusmai/laravel-file-manager#143]
Is there a way of hiding / not showing files that do not match a specified file type? Or is there a plan to create such a feature?

I would like to be able to specify a file type that can be selected for an input field. This so that the user can only input the correct file type. 

If there is no such feature, and no plan to create it, is it ok if I create a pull request and create the feature myself? 

I hope to hear from you. 

Paul

**Comment by alexusmai** [comment]
Hi, maybe in future...

**Comment by MordiSacks** [comment]
I filter like this,

add this before any other script
```html
    <script src="https://unpkg.com/xhook@latest/dist/xhook.min.js"></script>

    <script>
        
        xhook.after(function (req, res) {
            let allowed = /jpe?g|bmp|gif|png|svg/; // you can pass this from backend
            
            if (req.url.match(/\/content/)) {
                var data = JSON.parse(res.data);

                data.files = data.files.filter(function (f) {
                    return f.extension.toLowerCase().match(allowed);
                });

                res.data = JSON.stringify(data);
                res.text = JSON.stringify(data);
            }

        });
    </script>
```
