### ISSUE TITLE
Increase upload file pdf ?

### ISSUE THREAD

**Issue by giogiosw** [alexusmai/laravel-file-manager#148]
Hello
Is it possible to increase the maximum number of files to upload?
If I upload 40 pdf files I find only 20 uploads.

Is it possible to increase?

**Comment by alexusmai** [comment]
Hi,

Yes, [php docs](https://www.php.net/manual/en/ini.core.php#ini.max-file-uploads)

**Comment by giogiosw** [comment]
Ok thk ;)
