### ISSUE TITLE
How to add a tracking script to downloads? Summernote version

### ISSUE THREAD

**Issue by LuukPrins** [alexusmai/laravel-file-manager#15]
I want to add a script to the download function that can track the amount of times a file has been downloaded. This by working with a Database table.

public function download(RequestValidator $request, Filedownload $id)
    {
        $record = Filedownload::findOrNew(1);
        $record->file_name = $request->name;
        $record->times_downloaded = $record->times_downloaded +1;
        $record->save();
        return $this->fm->download(
            $request->input('disk'),
            $request->input('path')
        );
    }

this is my function right now, but it doesn't work. I also have a question about the ACLRules which don't seem to work for me either.

I've set 'acl'=> true, and my rules are:

 'aclRules'      => [
        null => [
            //['disk' => 'public', 'path' => '/', 'access' => 2],
        ],
        1 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        2 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        3 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        4 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        5 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        6 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        7 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        8 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        9 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 1],
        ],
        10 => [
            ['disk' => 'public', 'path' => '/storage/', 'access' => 2],
        ],
        11 => [
            ['disk' => 'public', 'path' => '/', 'access' => 2],
        ],
        12 => [
            ['disk' => 'public', 'path' => '/', 'access' => 2],
        ],
    ],

**Comment by alexusmai** [comment]
Hi,
Download request has only two params - path and disk

You can try the following method - create new middleware:

```
public function handle($request, Closure $next)
    {
        if ($request->routeIs('fm.download')) {

            $disk = $request->input('disk');
            $path = $request->input('path');

            // here find in DB your item and  +1
           ...
        }

        return $next($request);
    }
```

I added examples in the documentation how to use the system of ACL rules [doc](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md)
