### ISSUE TITLE
How to access disk and path of the selected file?

### ISSUE THREAD

**Issue by EkaterinaStancheva** [alexusmai/laravel-file-manager#152]
I've got Standalone button.  All of the examples shows how to return url of the selected file. Is it possible to access disk and path of this file?

**Comment by alexusmai** [comment]
Hi, No, this method return only URL

**Comment by EkaterinaStancheva** [comment]
Hi. Would it be possible to provide one more method which return disk and relative path to the selected file? Thank you in advance!

**Comment by EkaterinaStancheva** [comment]
In the compiled js file I've make the following changes:
```js
selectAction: function() {
    var e = this;
    var disk = this.selectedDisk;
    var path = this.selectedItems[0].path;
    
    this.$store.dispatch("fm/url", {
        disk: disk,
        path: path
    }).then((function(t) {
            "success" === t.data.result.status && e.$store.state.fm.fileCallback({"url": t.data.url, "path": path, "disk": disk})
        }
    ))
}
```
```js

selectAction: function(e, t) {
    var n = this;
    var path = e;
    var disk = this.selectedDisk;
    this.$store.state.fm.fileCallback ? this.$store.dispatch("fm/url", {
        disk: disk,
        path: path
    }).then((function(e) {
            "success" === e.data.result.status && n.$store.state.fm.fileCallback({'url': e.data.url, 'path': path, 'disk': disk})
        }
    )) 

    // ...
}
```

Could you please give an advice how to achieve similar result, without breaking backward compatibility?

**Comment by alexusmai** [comment]
For editing you can fork [alexusmai/vue-laravel-file-manager](https://github.com/alexusmai/vue-laravel-file-manager), but anyway you can't get backward compability
