### ISSUE TITLE
Undefined offset: 0 at ContentTrait

### ISSUE THREAD

**Issue by sayron97** [alexusmai/laravel-file-manager#153]
Добрый день. Проблема в том что при попытке создания файла или папки юзером выбивает 500ую ошибку со скрина ниже. Так же не отображается ни один файл. Я думаю что проблема с настройкой, но сделал я так как было указано в гайдах. В чем может быть проблема?
![Снимок экрана от 2020-04-16 12-21-47](https://user-images.githubusercontent.com/23458099/79439080-141a7680-7fdd-11ea-9f58-ef9844c56fd3.png)
![Снимок экрана от 2020-04-16 12-22-13](https://user-images.githubusercontent.com/23458099/79439084-154ba380-7fdd-11ea-8b84-acf155703b5f.png)
![Снимок экрана от 2020-04-16 12-22-33](https://user-images.githubusercontent.com/23458099/79439088-154ba380-7fdd-11ea-9f25-8bb23dcd849d.png)

**Comment by alexusmai** [comment]
Добрый день.
Если ничего не отображается - могут быть проблемы или с настройками диска или с настройками ACL (у вас whitelist стоит - отображать только то, что разрешено). Если без ACL все работает, то проблема с настройками ACL - на скрине не вижу настройку - 'aclRepository' - так как используете не дефолтную а свою, то проверьте правильно ли установлено имя вашего класса.
Например:
```
/**
 * ACL rules repository
 */
'aclRepository' => UsersACLRepository::class,
```

**Comment by sayron97** [comment]
С настройками вроде как все окей, вот скрин. 
Кроме того хоть и выбивается ошибка Undefined offset: 0, файлы все равно создаются на диске
![Снимок экрана от 2020-04-16 13-20-29](https://user-images.githubusercontent.com/23458099/79445405-4b8d2100-7fe5-11ea-8f14-b48ebbaf0723.png)

**Comment by sayron97** [comment]
И да, без ACL в самом деле все работает, то есть проблема где то в нем, но я не могу понять в чем...

**Comment by alexusmai** [comment]
А какая версия Laravel используется? Я сейчас проверил на 6 - все работает с такими настройками. На 7-ке я толком не тестил.

**Comment by alexusmai** [comment]
На 7-ке проверил - работает.
