### ISSUE TITLE
Remove "New File" option

### ISSUE THREAD

**Issue by antoniodesa** [alexusmai/laravel-file-manager#154]
How can i remove the "New file" option?

**Comment by alexusmai** [comment]
There is no such function. 
You can hide only with css, but it's not safe

```
.fm > .fm-navbar button[title="New file"]{
            display: none;
        }
```

**Comment by antoniodesa** [comment]
Yes, i did that. I also implemented a FileManagerServiceProvider with the following:
`public function boot()
    {
        \Event::listen('Alexusmai\LaravelFileManager\Events\FileCreating', function ($event) {
                return abort(401);
        });
    }`
To be safe.
