### ISSUE TITLE
Event management

### ISSUE THREAD

**Issue by lscavelli** [alexusmai/laravel-file-manager#16]
It would be useful to manage Events related to the main activities such as makeDir, filemoving, fileupload etc ... In my App, I would listen events and I could handle **CRUD operations on DB**, 
thank you very much

```php
ex.
namespace Alexusmai\LaravelFileManager\Events;
class FileIsUploading
{
    private $path;
    public function __construct($path) {
        $this->path = $path;
    }
    public function path() {
        return $this->path;
    }
}
^^^^^^^^^^^^^^^^
in the file of Upload ...
use Alexusmai\LaravelFileManager\Events\FileIsUploading;
event(new FileIsUploading($path));
```

**Comment by alexusmai** [comment]
Ok i'll add it soon.

**Comment by alexusmai** [comment]
I added some events, see more in docs - [Events](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md)

**Comment by lscavelli** [comment]
Thank you very much, I rehearse and let you know. You were very fast..
