### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by Djomobil** [alexusmai/laravel-file-manager#163]
Hello,

I've a little question about the enconding...

i've file encoding in iso-8859-1, i would like to know if it's possible to upload edited file with the original encoding, because it's uploaded in utf8.. 

Thk lot

**Comment by alexusmai** [comment]
This code is responsible for saving the file

https://github.com/alexusmai/vue-laravel-file-manager/blob/90b38f4f622361fb62b4eff3c9f14086efd490e8/src/components/modals/views/TextEdit.vue#L124
