### ISSUE TITLE
Integration with TinyMCE - How to show the file browser?

### ISSUE THREAD

**Issue by iainheng** [alexusmai/laravel-file-manager#164]
Hi, I copied the example code from https://github.com/alexusmai/laravel-file-manager/blob/master/examples/wysiwyg/tinymce.blade.php

However, I don't see any button to trigger the file manager window from the editor. 

This is what I can see on my screen:
![image](https://user-images.githubusercontent.com/3263759/81095455-9b516f00-8f37-11ea-96de-a6706bb881f7.png)

Is there anything special I need to enable/add for TinyMCE integration?

**Comment by mafftor** [comment]
Click on image the second icon from the end and then click on browse icon and your file manager will be opened

**Comment by iainheng** [comment]
Thanks @mafftor 😊 I am able to find it with your advise 👍 

I need to click the button to launch the file manager
![image](https://user-images.githubusercontent.com/3263759/81216948-63692b00-900e-11ea-862e-eddde2fe72a3.png)
