### ISSUE TITLE
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.

### ISSUE THREAD

**Issue by mdhosseini** [alexusmai/laravel-file-manager#167]
hello
when i try to install this filemanager i get this warning:
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
how can i change  jeremeamia/superclosure to opis/closure?

**Comment by Fredericld** [comment]
I have the same issue

**Comment by alexusmai** [comment]
"intervention/imagecache" - has this requirement, I can't fix it.
