### ISSUE TITLE
In Container.php line 1011:    Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.

### ISSUE THREAD

**Issue by Fredericld** [alexusmai/laravel-file-manager#168]
Hi,

I have just added this package to my composer file and got this error.
I am running Laravel 7

C:\fcms2>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 1011:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by httzipdev** [comment]
Same to me, upppp

**Comment by alexusmai** [comment]
Hi, try to use this instruction - [Update](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/update.md)

**Comment by Fredericld** [comment]
Hi,

Laravel Framework 7.19.0

PHP 7.3.2 (cli) (built: Feb  5 2019 22:55:35) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies


I am updating this issue. I have reinstalled the package today with the latest instructions you provided in previous post. It still fails....

See below my composer update 

C:\laravel_project>composer require alexusmai/laravel-file-manager
Using version ^2.5 for alexusmai/laravel-file-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
C:\laravel_project>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-util (v1.17.1): Downloading (100%)
  - Installing symfony/polyfill-php56 (v1.17.1): Downloading (100%)
  - Installing jeremeamia/superclosure (2.4.0): Loading from cache
  - Installing intervention/image (2.5.1): Loading from cache
  - Installing intervention/imagecache (2.4.2): Downloading (100%)
  - Installing alexusmai/laravel-file-manager (v2.5.1): Downloading (100%)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 1013:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

C:\laravel_project>php artisan vendor:publish --tag=fm-config --force

In Container.php line 1013:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.



C:\laravel_project>php artisan vendor:publish --tag=fm-assets --force

In Container.php line 1013:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.



C:\laravel_project>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 1013:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1



I have removed the package for now.
