### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by jim1506** [alexusmai/laravel-file-manager#17]
I have set up a disk:

![03-03-2019 10-41-51](https://user-images.githubusercontent.com/123184/53694093-ae036d80-3da1-11e9-9262-3c2c2d09b89f.png)

and have added this disk to the configuration but it is not showing the images:
![03-03-2019 10-45-50](https://user-images.githubusercontent.com/123184/53694101-beb3e380-3da1-11e9-9394-f7085576750a.png)

Am I doing something wrong?

**Comment by alexusmai** [comment]
Hi,
You need to change 'url' property. add your domain name, protocol, port.... 
Like this:

```php
'public' => [
            'driver' => 'local',
            'root' => public_path('images/pages'),

            'url' => 'http://my-domain.name/images/pages',
           // OR
            'url' => env('APP_URL').'/images/pages',  // set URL in .env file

            'visibility' => 'public',
        ],
```

**Comment by jim1506** [comment]
Thanks Alex and greetings from a wet and windy London.

I changed the filesystemphp to

         'public' => [
           'driver' => 'local',
              'root' => storage_path('app/public'),
              'url' => env('APP_URL').'/storage',
              'visibility' => 'public',
         ],

         'pageImages' => [
           'driver' => 'local',
           'root' => public_path('images/pages'),
           'url' => env('APP_URL').'/images/pages',  // set URL in .env file
           'visibility' => 'public',
         ],

but I am still getting:



my .env has

APP_DEBUG=true
APP_URL=http://localhost
   and I am using Windows IIS with localhost:8000

**Comment by alexusmai** [comment]
You can also try use only path, it's works too,

```php
 'url' => '/images/pages',
```

Now looked more closely.
Do not working creating previews for images. The URL parameter does not affect this. To create a preview used library -[intervention/image](https://github.com/Intervention/image)

Preview method looks like:

```php
 /**
     * Image preview
     *
     * @param $disk
     * @param $path
     *
     * @return mixed
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */
    public function preview($disk, $path)
    {
        // get image
        $preview = Image::make(Storage::disk($disk)->get($path));

        return $preview->response();
    }
```

and frontend part

```html
<img alt="418591-new" src="http://domain.name/file-manager/thumbnails?disk=public&path=images/418591-new.jpg" class="img-thumbnail">
```

## Package Requirements
 * PHP >= 7.0.0
 * Laravel 5.5 or higher
 * GD Library or Imagick for [intervention/image](https://github.com/Intervention/image)
 * requires [intervention/image](https://github.com/Intervention/image) and [intervention/imagecache](https://github.com/Intervention/imagecache)

You need to check manualy works with this librarys in your evironment. I can't do this.

**Comment by jim1506** [comment]
Thanks Alex but I have tried everything.


first I checked that GD was there in PHP config:

then I amended the filesystem as you suggested:

and I checked that the appropriate file was in the composer file:


I even updated composer to make sure and although the system is reading 
the files OK I am still now seeing the images:

**Comment by alexusmai** [comment]
Other actions work? Preview images, play MP3, edit text?
If you look in the browser console, the network tab is there when downloading images, what is the answer from the server?
Are there any errors in the logs of Laravel?

No images are displayed in your responses. Apparently due to the fact that you respond by sending email.
