### ISSUE TITLE
custom route prefix

### ISSUE THREAD

**Issue by skyosev** [alexusmai/laravel-file-manager#171]
Currently the prefix is fixed in the route.php file:

`'prefix'     => 'file-manager',`

It would be helpful if one could configure it. 

For example in my app, I change the session cookie for the /admin/* route and the file manager upload throws CSRF exceptions, because it generates different session for the /file-manager/ route. Currently I need to add exclusion, but a clean solution would be to change the prefix to /admin/file-manager/

I guess other use cases could also arise, as to configure route prefix is quite common among the packages.

**Comment by alexusmai** [comment]
Hi,
Added, You can try to use this function - [link](https://github.com/alexusmai/laravel-file-manager#in-a-new-version-25)

**Comment by skyosev** [comment]
Many thanks! Works fine and I hope it will be useful to others too. Great work!

**Comment by mdabbagh-ir** [comment]
hi
When I change the prefix to  'prefix' => 'file' or 'prefix' => 'admin.file' the fm-button page still sends the following request. 
Request URL: http://127.0.0.1:8000/file-manager/initialize.

I changed the routes.php file as follows and only the routes was modified but the requests within the routes were not modified.
`Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::group([
        'prefix'     => 'file-manager',
        'namespace'  => 'Alexusmai\LaravelFileManager\Controllers',
    ], function () {...`
