### ISSUE TITLE
Thumbnail Error

### ISSUE THREAD

**Issue by jm-vergara** [alexusmai/laravel-file-manager#175]
Hi, I uploaded the project file in the production server but I encounter an error in thumbnail and preview. It's all working in the localhost server but in the production server I got this error.

![image](https://user-images.githubusercontent.com/67063284/84915021-db873e00-b0ee-11ea-8a1c-542a4413ff30.png)

When I check the direct url https://sample.com/file-manager/thumbnails?disk=public&path=Images%2FMay%207i.jpg&v=1592359747
![image](https://user-images.githubusercontent.com/67063284/84915255-25702400-b0ef-11ea-8495-0bdcf780f7b2.png)

**Comment by alexusmai** [comment]
Hi,
Check your server settings. You need to have on the server GD Library or Imagick library for work with images, more information about library - [link](http://image.intervention.io/)
And check your laravel log. What mistakes do you see there?

**Comment by jm-vergara** [comment]
Yey It worked!

this is the LaravelLog
local.ERROR: PHP Fileinfo extension must be installed/enabled to use Intervention Image

and I just miss the Fileinfo Extension

Thank you
