### ISSUE TITLE
Middleware not working, even auth, only 'web' is working

### ISSUE THREAD

**Issue by Vandelson7593** [alexusmai/laravel-file-manager#176]

**Comment by alexusmai** [comment]
Hi,
That should work. Check yuor app.

**Comment by Vandelson7593** [comment]
> Hi,
> That should work. Check yuor app.

Admin and Auth middleware is returning null

**Comment by alexusmai** [comment]
My application only set middlewares names for routes.. that's all.
Call this command, and you can see what the middlewares applied for routes

```
php artisan route:list
```

**Comment by Vandelson7593** [comment]
It's complicated, do you have a middleware's code that works?

**Comment by Vandelson7593** [comment]
public function handle($request, Closure $next)
    {
        if (auth()->user() != null && auth()->user()->is_admin == 1) {
            return $next($request);
        }
        return redirect(route('home'));
    }

my admin middleware
