### ISSUE TITLE
PDF viewer

### ISSUE THREAD

**Issue by vosaan** [alexusmai/laravel-file-manager#177]
Подскажите, пожалуйста, можно ли как-то организовать просмотр pdf-файлов, которые были загружены с помощью файл-менеджера, и если да, то как?

**Comment by alexusmai** [comment]
Привет.
Можно попробовать в новой версии, работает по dbl-click. 
Работает не во всех браузерах..

**Comment by vosaan** [comment]
Спасибо. А планируется ли поддержка просмотра файлов типа doc(x) и xls(x)?

**Comment by alexusmai** [comment]
Пока нет. Может как времени больше свободного будет то посмотрю, что можно сделать..
