### ISSUE TITLE
multiple standalone buttons

### ISSUE THREAD

**Issue by VincentVanWijk** [alexusmai/laravel-file-manager#18]
Hi, i am trying to add 2 standalone buttons to my view, but the same function to set the link is called.
How can i do this?

i tried: 
`<script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function() {

            document.getElementById('lfm').addEventListener('click', (event) => {
                event.preventDefault();

                window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
            });

            document.getElementById('lfm2').addEventListener('click', (event) => {
                event.preventDefault();

                window.open('/file-manager/fm-button', 'fm2', 'width=1400,height=800');
            });
        });

        // set file link
        function fmSetLink($url) {
            //this one is called
            document.getElementById('thumbnail').value = $url;
        }

        function fm2SetLink($url) {
            //this one is not
            document.getElementById('thumbnail2').value = $url;
        }

    </script>`

**Comment by alexusmai** [comment]
Hi, you can try this example:

```
<!-- HTML -->
<div class="container">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="image_label">Image</label>
            <div class="input-group">
                <input type="text" id="image1" class="form-control" name="image"
                       aria-label="Image" aria-describedby="button-image">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-image">Select</button>
                </div>
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="image_label">Image2</label>
            <div class="input-group">
                <input type="text" id="image2" class="form-control" name="image"
                       aria-label="Image" aria-describedby="button-image">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-image2">Select</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- JS -->
<script>
  document.addEventListener("DOMContentLoaded", function() {

    document.getElementById('button-image').addEventListener('click', (event) => {
      event.preventDefault();

      inputId = 'image1';

      window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
    });

    // second button
    document.getElementById('button-image2').addEventListener('click', (event) => {
      event.preventDefault();

      inputId = 'image2';

      window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
    });
  });

  // input
  inputId = '';

  // set file link
  function fmSetLink($url) {
    document.getElementById(inputId).value = $url;
  }
</script>
```

**Comment by VincentVanWijk** [comment]
Works like a charm!
Thanks a lot for your quick reply! 
Awesome package.

**Comment by alemhulu** [comment]
Thanks for the great support!!!! 
I have one issue while I open standalone button files are sorted by the name i want it by time/date sort can you please help me? thank you.
