### ISSUE TITLE
Unrestricted File Upload Bypass because open middleware web in config 

### ISSUE THREAD

**Issue by vahidalvandi** [alexusmai/laravel-file-manager#187]
I was hacked because in config/file-manager.php  middleware was 'web' , i forget to change it to middleware 'auth','admin'

`    'middleware' => ['web'],`

if you set it to [] and return a error , then programmer understands need add admin middleware
![Screenshot from 2020-07-18 16-40-48](https://user-images.githubusercontent.com/7871623/87874678-fcd69500-c9e0-11ea-86c5-f3d03b8fec73.png)

**Comment by vahidalvandi** [comment]
![Screenshot from 2020-07-18 16-40-48](https://user-images.githubusercontent.com/7871623/87874689-17a90980-c9e1-11ea-8e35-0e54f1cd1a18.png)

**Comment by alexusmai** [comment]
Hi,
You must take care of the security of your application yourself.
Everyone has different tasks and middleware names, I made appropriate warnings in the documentation and configuration file.
