### ISSUE TITLE
Можно распаковать JS файлы?

### ISSUE THREAD

**Issue by siteincity** [alexusmai/laravel-file-manager#2]
Было бы неплохо разжать JS файлы чтобы было 2 версии минифицированные и обычные. Вот пример интеграции 
fm.$store.commit('fm/setFileCallBack', function (fileUrl) {
          // const funcNum = getUrlParam('CKEditorFuncNum');
          // window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl);
          // window.close();
        });
Может быть есть еще какие-либо полезные функции.

**Comment by alexusmai** [comment]
Есть отдельно пакет - [vue-laravel-file-manager](https://github.com/alexusmai/vue-laravel-file-manager)

Интеграция с CKEditor есть в доках - [Integration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md)

**Comment by siteincity** [comment]
Спасибо за инфу, не догадался посмотреть в другом месте. Спустя день я его интегрировал на кнопку "добавить изображение" чтобы открывался в отдельном всплывающем окне (window.open) и используя callback, который в единственном экземпляре я обнаружил в доках по интеграции в ckeditor, пакет возвращал в родительское окно (откуда был вызван) урл выбранного файла. Есть просто небольшое неудобство, нельзя выбрать несколько файлов и массивом отправить как результат выбора
