### ISSUE TITLE
Dosn't show any thing after installation 

### ISSUE THREAD

**Issue by omar-zr** [alexusmai/laravel-file-manager#208]
after do all steps of installation and  configuration without any error the view file still empty ! 
![image](https://user-images.githubusercontent.com/59957877/98300494-07359280-1fc2-11eb-9b73-9b712470e258.png)
![image](https://user-images.githubusercontent.com/59957877/98300902-a490c680-1fc2-11eb-8414-6193730d4b16.png)
also i try to check the paths and all configs are ok 
![image](https://user-images.githubusercontent.com/59957877/98301036-d99d1900-1fc2-11eb-9d88-929b9c5b49e3.png)

**Comment by Saputra20** [comment]
Yes I get the same error . Please Help me

**Comment by alexusmai** [comment]
Hi.
What errors do you have in the browser console?

**Comment by Saputra20** [comment]
![console2](https://user-images.githubusercontent.com/44329567/98490724-feb0b680-2264-11eb-827e-d98fb6a1fb88.JPG)
![console](https://user-images.githubusercontent.com/44329567/98490725-007a7a00-2265-11eb-84b1-1158c0ddc4e1.JPG)

no error in the browser console.

**Comment by omar-zr** [comment]
> Hi.
> What errors do you have in the browser console?

Thanks for reply  , 
There is no error in console

**Comment by LfJohnVo** [comment]
I have the same error and found this:

![image](https://user-images.githubusercontent.com/32848900/98631808-cef4c380-22e3-11eb-9473-50ba384aae49.png)
![image](https://user-images.githubusercontent.com/32848900/98631825-dae08580-22e3-11eb-96e9-52fd68a42468.png)

**Comment by alexusmai** [comment]
@LfJohnVo 

LFM call this URL's localhost/file-manager, but you have localhost/tabantaj/public/admin/... it's not good url, use Homestead for development, or you can use [vue package](https://github.com/alexusmai/vue-laravel-file-manager) - and you will set your url

**Comment by LfJohnVo** [comment]
> @LfJohnVo 
> 
> LFM call this URL's localhost/file-manager, but you have localhost/tabantaj/public/admin/... it's not good url, use Homestead for development, or you can use [vue package](https://github.com/alexusmai/vue-laravel-file-manager) - and you will set your url

Thanks!!!, but what can I do if my team uses xampp? How I can resolve?

**Comment by alexusmai** [comment]
@Saputra20 @omar-zr 

You provide me to less information than i need to resolve your problem..
Why do you show me the screen with this url: http;//localhost:8000/file-manager/content... show me your main page for file-manager, check all the js and css files, check laravel log, check browser - log and network tab's

**Comment by alexusmai** [comment]
@LfJohnVo 
You can only set your url in vue-laravel-file-manager package - https://github.com/alexusmai/vue-laravel-file-manager/blob/master/README.md#settings---object

**Comment by Saputra20** [comment]
@alexusmai 

Thanks. 

thank you, i have solved the problem

**Comment by LfJohnVo** [comment]
@alexusmai 
Thank you man
i have solved the problem, it was the url
