### ISSUE TITLE
Auto select folder in the list

### ISSUE THREAD

**Issue by lscavelli** [alexusmai/laravel-file-manager#21]
And if I wanted to dynamically restrict access to a single folder, what can I do?
ex. disk =>public - path=>files\general\products\*
In the list display only the files contained within the folder products
auto select the folder "products" and No return to general or files or public

**Comment by alexusmai** [comment]
I did not quite understand what you need ..

If you need to show only "products" folder - add a new disk(in config/filesystems.php):

```
'products' => [
            'driver' => 'local',
            'root' => public_path('files/general/products'), // set here your path
            ...
        ],
```

And add this disk to file manager config file.

```
'diskList'  => ['products'],
```

**Comment by lscavelli** [comment]
First of all, sorry for the language, use of automatic translators. If I had only one folder I could proceed in the way you indicated,  but when you interact with different folders the question changes..
example:
regardless of users, I have to dynamically access and restrict the visibility to a folder before, for which
ex..
general/folder A
general/folder B
general/folder C
........
general/folder N

It would take a way to set the folder to be displayed on the fly  ... as an example

^^^^^^^^^^^^^^^^^^^^^
'accessDefaultFolder' => \App\Handlers\FileManagerHandler::class,

in the vendor/package
$folder = config('file-manager.accessDefaultFolder');
if (class_exists($folder)) {
    $folder = app()->make($folder)->setFolderName();
}
Access and display only  folder, subfolder and files contents ...

^^^^^^^^^^^^^^^^^^^^^
In the my class FileManagerHandler
public function setFolderName() {
   return $this->dynamicSystemSetFolder()
   // or ... if (..) return .. elseif () return ... etc...
}

**Comment by alexusmai** [comment]
I do not quite understand what is required. My English is also bad :-).

But I guess you need to read the documentation section of the [ACL](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md). Pay special attention to the [second example](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md#example-2).
