### ISSUE TITLE
Unable to compile the file-manager.js because it is minified and obfuscated, Need non-minified version

### ISSUE THREAD

**Issue by lovekrissh143** [alexusmai/laravel-file-manager#211]
I'm not able to find a non minified version of the file-manager.js so that I can compile it.

I can use find and replace to achieve the route prefix but to have a greater control over this I need to have the clean file manager js file. I've performed a unminification for this and here's what I got.

@alexusmai if you're seeing this then please please include the raw js in next release. Everyone needs to have a greater control over the things happening, right nah man?

[file-manager-raw_2020_11_15_09_03_34.zip](https://github.com/alexusmai/laravel-file-manager/files/5541810/file-manager-raw_2020_11_15_09_03_34.zip)

**Comment by alexusmai** [comment]
Hi,
Please read documentation - https://github.com/alexusmai/laravel-file-manager#features (first row)

**Comment by lovekrissh143** [comment]
Amazing Dude, That's why I love Russians, @alexusmai , thank you so much for explaining it, I don't know how I can show you my heart full of thanks :).
👍🏻 
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
Thanks Man!
