### ISSUE TITLE
iOS (iPad and iPhone) does not allow files and folder to be interacted or downloadable.

### ISSUE THREAD

**Issue by minwooro** [alexusmai/laravel-file-manager#22]
Hello,

When viewing the file manager in iOS and iPhone safari, you cannot interact with the files or folders at all.

**Comment by alexusmai** [comment]
Hi, sorry but i don't have any IOS or MAC devices for check this problem..

And yet, the file manager is not optimized for working with mobile devices.

**Comment by minwooro** [comment]
I see, thank you for your reply. It works fine on Mac safari. It also works on Android device.

Only on iOS safari the file manager is none functioning.
