### ISSUE TITLE
Status: Warning, Config Not Found

### ISSUE THREAD

**Issue by denzndhauz** [alexusmai/laravel-file-manager#23]
I followed all the installation guide but I got this error.

![image](https://user-images.githubusercontent.com/8641713/54508492-0d0bd980-4981-11e9-82ea-9417f91d8a3e.png)

Did I miss something?

**Comment by alexusmai** [comment]
After command

```
php artisan vendor:publish --tag=fm-config
```

The "file-manager.php" file should appear in the "config" folder.

**Comment by denzndhauz** [comment]
Thanks @alexusmai , It's working now. I will now close this issue. 👍
