### ISSUE TITLE
TinyMCE not showing selected picture in editor

### ISSUE THREAD

**Issue by KHUZEMAH** [alexusmai/laravel-file-manager#235]
I am Using this code to call file-manager in tinymce
file_picker_callback (callback, value, meta) {
        let x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth
        let y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight

        tinymce.activeEditor.windowManager.openUrl({
          url : '/file-manager/tinymce5',
          title : 'Laravel File manager',
          width : x * 0.8,
          height : y * 0.8,
          onMessage: (api, message) => {
            callback(message.content, { text: message.text })
          }
        })
      },
The image is successfully selected but then in editor there is this issue.
![image](https://user-images.githubusercontent.com/32608977/116528190-f7559600-a8f4-11eb-9ca3-9f39eec0ef2c.png)
![Capture](https://user-images.githubusercontent.com/32608977/116528282-16542800-a8f5-11eb-8516-ce449c551b30.PNG)

**Comment by mateuslecchi** [comment]
Hei @KHUZEMAH did you manage to fix the problem?

**Comment by KHUZEMAH** [comment]
Yes the issue was fixed

**Comment by mateuslecchi** [comment]
Can you show me? I'm stuck on this.

**Comment by KHUZEMAH** [comment]
The issue was woth the path where the image was being saved. I changed my url and the pictures were successfully shown in the editor

**Comment by mateuslecchi** [comment]
With my code when I select the image the callback wont load any of the image properties.


![image](https://user-images.githubusercontent.com/45340326/126543715-212e0554-f782-4aab-90cc-24db89b6b87e.png)
![image](https://user-images.githubusercontent.com/45340326/126543734-ef68d7b4-fc79-4591-9f80-db9ef27a9758.png)
![image](https://user-images.githubusercontent.com/45340326/126543748-0ccdcd6b-8347-40fe-b5ae-5168d4bc105c.png)

**Comment by ayrongabriel** [comment]
In case anyone else has this problem, just run: `php artisan storage:link`

**Comment by mateuslecchi** [comment]
For me was the site base path, on Dev Env I change for localhost instead of 127.0.0.1 and works.
