### ISSUE TITLE
Can't get ACL to work

### ISSUE THREAD

**Issue by VincentVanWijk** [alexusmai/laravel-file-manager#24]
Hi there, thanks for this awesome package,
When i try to configure acl, i always get 'Acces denied', except when i use path=>'*'. I'm not sure what i am doing wrong.

**filesystems.php**
```
    'disks' => [
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public/media'),
            'url' => env('APP_URL') . 'storage/media',
            'visibility' => 'public',
        ]]
```
**file-manager.php**
   ```
 'diskList'  => ['public'],
    'middleware' => ['web', 'auth', 'fm-acl'],
    'acl' => true,
    'aclHideFromFM' => false,
    'aclStrategy'   => 'whitelist',
    'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\ConfigACLRepository::class,
'aclRules'      =>
    [
        1 => [
            ['disk' => 'public', 'path' => 'altena', 'access' => 2]
        ],
        ' aclRulesCache ' => null,
    ]

```
My User::id = 1, so that would mean i only have access to 'altena' folder right?

this is what i get: (Access Denied)
![image](https://user-images.githubusercontent.com/10919865/54537265-852ecb00-4992-11e9-98e9-8f7bef3b3e77.png)

 
When i change path to '*', i get:
![image](https://user-images.githubusercontent.com/10919865/54537294-9081f680-4992-11e9-8e9a-a167dffef588.png)

no other path works except *.

Hope you can help!
-Vincent

**Comment by VincentVanWijk** [comment]
It works! I feel silly that i didn't think of the root folder..
Thanks a lot for your fast reply!
-Vincent

**Comment by mobinco** [comment]
It is not better to mention this in the documents?
