### ISSUE TITLE
Is there anyway to dynamically select a certain disk on default load

### ISSUE THREAD

**Issue by minhtu-cloudtek** [alexusmai/laravel-file-manager#25]
Hi dev master,

Is there anyway to select a certain disk on default load dynamically? For example URLs like` /file-manager/fm-button?disk=disk2` or `/file-manager/fm-button/#disk=disk2` will return the File manager page with the initially selected disk 2, although I put my `diskLis`t as `['disk1','disk2','disk3']`.

I think there are some kinds of api function which I can use to access the Vue app to programmatically select a disk.

**Comment by alexusmai** [comment]
Hi,

Now there is no such function. The default disk can be set only in the settings, you cannot dynamically change it.
But I will think about this question.

**Comment by estaticfear** [comment]
> Hi dev master,
> 
> Is there anyway to select a certain disk on default load dynamically? For example URLs like` /file-manager/fm-button?disk=disk2` or `/file-manager/fm-button/#disk=disk2` will return the File manager page with the initially selected disk 2, although I put my `diskLis`t as `['disk1','disk2','disk3']`.
> 
> I think there are some kinds of api function which I can use to access the Vue app to programmatically select a disk.

I think it's a good idea !!!

**Comment by alexusmai** [comment]
Hi, update package, and try

```
// !!! The disk must be in diskList !!!

// one window
http://site-name.com/your-url?leftDisk=public

// two windows
http://site-name.com/your-url?leftDisk=public&rightDisk=images
```

**Comment by minhtu-cloudtek** [comment]
Hi Mr Dev Master,

I updated the package, republic the assets and it works!

Thank you so much!
