### ISSUE TITLE
how use file manger as upload file

### ISSUE THREAD

**Issue by kazemimorteza68** [alexusmai/laravel-file-manager#26]
Hi
i did installed file mange and add all link and style to project.now how to use file manger. it didn't appear in my form. please help me.Thanks.

**Comment by alexusmai** [comment]
Hi, please provide more information.
Show your view file, where you connect FM, your config files filesystems.php -> disks array, file-manager.php -> diskList array
Do you have any errors in the browser console?

**Comment by kazemimorteza68** [comment]
Thank you for your fast response.
I wan to use this file manager in input tag
`
 <input type="file" value="uploadFile">
`
Yes i have Javascript Error:
`
CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token file-manager.js:20:10551
W
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:20:10551
56d7
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:20:10948
n
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:105
0
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:948
n
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:105
<anonymous>
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:908
<anonymous>
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:2
TypeError: t is null[Learn More] file-manager.js:20:10677
W
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:20:10677
56d7
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:20:10948
n
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:105
0
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:948
n
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:105
<anonymous>
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:908
<anonymous>
http://127.0.0.1:8000/vendor/file-manager/js/file-manager.js:1:2
`

**Comment by alexusmai** [comment]
Did you do this?

- add a csrf token to head block if you did not do it before

```
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
```

Integration with form input, see docs - [standalone button](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md#standalone-button)

**Comment by kazemimorteza68** [comment]
Thanks . i recently added csrf but still i have error.

**Comment by alexusmai** [comment]
Show your view and config files

**Comment by kazemimorteza68** [comment]
Thanks .
csrf and filemanager.js have conflict.
what is your means from config file?

this is View file:
```php
<!doctype html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{config("app.name")}}</title>
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">

    </div>
</head>
<body>

<div class="col-12">
    <h2 class="alert alert-primary">Add new Group</h2>

    <form action="{{url('storeGroups')}}" method="post">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <label for="name">Name:</label>
        <input type="text" name="name" class="input-group">
        <br>

        <label for="parent_name">Parent_name</label>
        <br>
        <select name="parent_name"  class="input-group">
            <option value="" selected>---</option>
           @foreach($groups as $group)
                <option value="{{$group}}">{{$group}}</option>
               @endforeach
        </select>

        <br>
        <input type="file" value="uploadFile">
        <div style="height: 600px;">
            <div id="fm"></div>
        </div>
        <br>
        <input type="submit" value="Save" class="input-group btn btn-dark">

    </form>
</div>
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
</body>
</html>
`

**Comment by alexusmai** [comment]
Please read docs!!!

[Installation](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/installation.md)
[Configuration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md)
[Integration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md)

In head block
```
<head>
...
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
....
</head>
```

It will not work

```
<input type="file" value="uploadFile">
        <div style="height: 600px;">
            <div id="fm"></div>
        </div>
..
```

You need youse  [standalone button](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md#standalone-button)

**Comment by alexusmai** [comment]
If you will use "standalone button" you don't need add csrf token to head block.

Example:

```
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>File Manager and standalone button</title>
</head>
<body>

<div class="container">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="image_label">Image</label>
            <div class="input-group">
                <input type="text" id="image_label" class="form-control" name="image"
                       aria-label="Image" aria-describedby="button-image">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-image">Select</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {

    document.getElementById('button-image').addEventListener('click', (event) => {
      event.preventDefault();

      window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
    });
  });

  // set file link
  function fmSetLink($url) {
    document.getElementById('image_label').value = $url;
  }
</script>
</body>
</html>
```

**Comment by kazemimorteza68** [comment]
Thank you MR Aleksandr Manekin 
it works.

**Comment by stevensherah** [comment]
Wait so if it doesn't work with the laravel CSRF then its not supposed to be a laravel package...

I have a  struggled with this for a whole week in a row and the longest time i know.
but with the WYSIWYG how comes even with the CSRF it works seemless.....

**Comment by stevensherah** [comment]
I Have followed all the steps above but the page says 

> The page has expired due to inactivity. 
> 
> Please refresh and try again.
