### ISSUE TITLE
Undefined index path on creating directory

### ISSUE THREAD

**Issue by vikasjangir202** [alexusmai/laravel-file-manager#269]
When making a directory this error flashes. Although the directory is created successfully if I close the alert and click on refresh icon then I can see the directory but still can't figure out this error.

here's code from custom "UsersACLRepository.php"
 
        `if (\Auth::check()) {
            $userFileDir=storage_path()."/app/ftp/".\Auth::user()->email;
            if(!\File::isDirectory($userFileDir)){
                \File::makeDirectory($userFileDir, 0777, true, true);
            }

            \Config::set('filesystems.disks.kirikom.root', 'public_html/storage/app/ftp/'.\Auth::user()->email);

            return [
                ['disk' => 'kirikom', 'path' => '*', 'access' => 2],                                  // main folder - read
                // ['disk' => 'kirikom', 'path' => \Auth::user()->email, 'access' => 1],  // read and write
                // ['disk' => 'kirikom', 'path' => \Auth::user()->email.'*', 'access' => 2],  // read and write
            ];
        }`

<img width="1440" alt="Screenshot 2021-10-29 at 2 36 48 PM" src="https://user-images.githubusercontent.com/55763495/139408561-9df716c9-8fc5-48f6-a8ed-be9eda2aa016.png">

**Comment by hadjistasi** [comment]
Any updates on this? Facing same issue.

**Comment by vikasjangir202** [comment]
@hadjistasi  I switched to Unisharp Laravel Filemanager.
