### ISSUE TITLE
Remove permission

### ISSUE THREAD

**Issue by vishal-px** [alexusmai/laravel-file-manager#27]
Hi @alexusmai 
I installed this package and its awesome.
Is it possible to don't give delete permission to the user? and how to configure with Amazon S3?

**Comment by alexusmai** [comment]
Hi, thank you.

> Is it possible to don't give delete permission to the user?

Yes, you can use [ACL](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md)

> and how to configure with Amazon S3?

See Laravel docs [Filesystem](https://laravel.com/docs/5.8/filesystem) - you need install some package for work with Amazon (driver)

I tested work with FTP, SFTP, Dropbox, YandexDisk.. Amazon should be work..

**Comment by vishal-px** [comment]
Hello, @alexusmai thank you for the reply.
In ACL doc I can't find the configuration for delete.
what I want, after login the user can read and write the file or directory but the user doesn't have the permission to delete that file or directory.

**Comment by alexusmai** [comment]
Hi.
O, ok, I understood you.

I think you can create new middleware for this, example:

```php

public function handle($request, Closure $next)
{
    $routeName = $request->route()->uri();

    $user = $request->user();

    // if ( $routeName === 'file-manager/delete' && $user->id === 1) OR
    // if ($routeName === 'file-manager/delete' && $user->role !== admin) OR
    // if ($routeName === 'file-manager/delete' && something else...)

    if ($routeName === 'file-manager/delete' &&  $user->id === 1 ) {
        abort(403, 'Forbidden!!! You can't delete!');
    }

    return $next($request);
}

```

And add this middleware to file-manager.php config file..

**Comment by vishal-px** [comment]
Hi.

I created the middleware and did modification in your suggested code and its work for me.

```
public function handle($request, Closure $next)
    {
        $routeName = $request->route()->uri();
        $user = $request->user();
        if ($routeName === 'file-manager/delete' && $user->type == 1) {
            return response()->json([
                'result' => [
                    'status'  => 'error',
                    'message' => trans('file-manager::response.aclError'),
                ],
            ]);
        }
        return $next($request);
    }

```
Thank you brother.
