### ISSUE TITLE
File Manager to work local without Internet

### ISSUE THREAD

**Issue by ardico** [alexusmai/laravel-file-manager#270]
I'm behind an enterprise proxy that is blocking the URL's:

```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">

```

I'm trying to setup a personnel web server on my local PC.

My only problem is that I get:

![Alexus](https://user-images.githubusercontent.com/12254443/139865348-19b2846e-8521-4bae-9b1a-63f4092a2096.jpg)

I've tried to change to local :
```
    <link rel="stylesheet" href="{{ asset ('/vendor/fontawesome-free/css/all.min.css') }}" >
```

But when I check the source code I get allways the reference to the initial links (even cleaning the cache), 

Where should I change to local links for bootstrap and the the fonts?

Regards,
Armando

**Comment by amrreko** [comment]
same problem what is the solution it blocks link to load

**Comment by mrhaghgooyan** [comment]
Follow this path and edit :
vendor\unisharp\laravel-filemanager\src\index.blade.php
replace with your local files
Of course, it is never suggested to change the core, but I really did not find a better solution for this problem.

good luck
