### ISSUE TITLE
404 error on js.map file + no user interface?

### ISSUE THREAD

**Issue by djtechonline** [alexusmai/laravel-file-manager#283]
Hello, I am trying to add laravel-file-manager to a project.  I followed your instructions, but when I load the page I get the following error:  Failed to load resource: the server responded with a status of 404 (Not Found)  for {my-domain}/vendor/file-manager/js/app.b80d5059.js.map

I have published the assets as per the instructions andI am trying to use the precompiled css and js files such as: <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script> but I am not sure why is is looking for a .js.map file or how to proceed.

EDIT:  I found and removed the reference to the map at the very end of the file-manager.js and the error is gone.  Seems to be working now.

**Comment by janrauhl** [comment]
Hi @djtechonline , I have similar errors, but it's not on the map:

file-manager.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
file-manager.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
filemanager:49 Uncaught TypeError: Cannot read properties of undefined (reading 'commit')
    at HTMLDocument.<anonymous> (filemanager:49:19)
file-manager.css:1 Failed to load resource: the server responded with a status of 404 (Not Found) 

by any chance, do you know how to solve it? 

Thank you!

**Comment by djtechonline** [comment]
Hi @janrauhl,

It seems like your 404 error is referring to the location of file-manager.js and file-manager.css themselves.  My suggestion is to make sure the path to those files is correct in your blade/php file.  If the location is not specified properly, then the page cannot find the files to render the user interface.   I hope this helps.  Best of luck!

**Comment by janrauhl** [comment]
Hi @djtechonline , 

Thanks for replying! Below are my code, I copied the path of file-manager.js and file-manager.css using the 'copy relative path' function. 

    <link rel="stylesheet" type="text/css" href="{{ url('css/filemanager.css') }}">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css">
    <link href="{{asset( 'vendor\alexusmai\laravel-file-manager\resources\assets\css\file-manager.css') }}"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <link rel="icon" type="image/png" href="/Images/favicon-32x32.png" sizes="32x32" /> 

            <script src="{{ asset('vendor\alexusmai\laravel-file-manager\resources\assets\js\file-manager.js') }}">


now it shows this error: 
GET http://127.0.0.1:8000/vendor/alexusmai/laravel-file-manager/resources/assets/css/file-manager.css net::ERR_ABORTED 404 (Not Found)
filemanager:57          GET http://127.0.0.1:8000/vendor/alexusmai/laravel-file-manager/resources/assets/js/file-manager.js net::ERR_ABORTED 404 (Not Found)

by any chance do you know why this happens? 

Thanks!
