### ISSUE TITLE
hide toolbar buttons

### ISSUE THREAD

**Issue by mkosmen** [alexusmai/laravel-file-manager#29]
How can i hide toolbar buttons. one or more ?
**(i want to hide not make it disable)**

**Comment by alexusmai** [comment]
Hi, you can use css

```
// hide upload button
.fm .fm-navbar button[title="Upload"] {
    display: none;
}
```

**Comment by mkosmen** [comment]
are u kidding me ?

any user who know about how to make a changes on html and open up console and make it to visible. i don't want it rendered on init.

ok?

**Comment by alexusmai** [comment]
You wanted to hide buttons, not disable.

Buttons can not be disabled during initialization.

**Comment by mkosmen** [comment]
i told u to "i don't want it rendered on init" it means " can not be disable. it doesn't rendered '. your answer is very funny even laughable.
