### ISSUE TITLE
After i updated to 3.0.1 icons are not displaying in upload

### ISSUE THREAD

**Issue by zumm-l3ss** [alexusmai/laravel-file-manager#295]
After upgrading, buttons not displaying.
I had to add manually : 
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css">`

Not it works. 
It s something i m doing bad? Or ?

* Updated from older version, to last one. (laravel 8 to laravel 9)

**Comment by alexusmai** [comment]
For new version used bootstrap 5 and bootstrap icons

example:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
```

**Comment by zumm-l3ss** [comment]
> For new version used bootstrap 5 and bootstrap icons
> 
> example:
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
> ```

I used that first time and it didn t work. 
At version 3.0.1 for me looks like it s still some fontawesome icons? 

Icon name: far fa-upload 

Thanks

**Comment by alexusmai** [comment]
did you update assets?

```
php artisan vendor:publish --tag=fm-assets --force
```

**Comment by zumm-l3ss** [comment]
yes, but still no clue what s wrong.
On inspect, it says 
`<i class="far fa-folder"></i>`

**Comment by alexusmai** [comment]
maybe cache, try to clear browser cache

**Comment by zumm-l3ss** [comment]
I uninstalled the module, now reinstalled and clean browser cache.

It s working now!

Thanks alot !
