### ISSUE TITLE
Оффтоп =)

### ISSUE THREAD

**Issue by siteincity** [alexusmai/laravel-file-manager#3]
Я просто не понимаю почему такие пакеты как ваш не в топе =) Почему люди хавают мусор, который не умеет ничего(laravel-filemanager) или долго грузится(elfinder), или гадит своими файлами по всем папкам приложения (оба) Искренне надеюсь на развитие вашего.

**Comment by alexusmai** [comment]
Да, мало, что-то написать, нужно уметь еще это раскрутить.. Насчет развития, пока ничего сказать не могу, сейчас времени нет.
