### ISSUE TITLE
How to use ckeditor | summernote with Vue js

### ISSUE THREAD

**Issue by vishal-px** [alexusmai/laravel-file-manager#32]
Hi @alexusmai 

My project is in laravel + Vue and I want to use ckeditor or summernote from this package so how can I use editor in .vue file?

**Comment by alexusmai** [comment]
Hi. My package doesn't exist  summernote or ckedtitor, you need to install them yourself.
For summernote you can googling something like this - [vuejs2-summernote-component](https://github.com/cho0o0/vuejs2-summernote-component)

**Comment by vishal-px** [comment]
In this package I see both: https://prnt.sc/n9dlg9

**Comment by alexusmai** [comment]
It's an example of how to integrate file manager with these editors - [Integration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md)
