### ISSUE TITLE
Thumbnails are broken but status 200

### ISSUE THREAD

**Issue by dakisan** [alexusmai/laravel-file-manager#35]
Hi,

My images are showing up as broken but they are being served with a status of 200.

![Capture](https://user-images.githubusercontent.com/37936718/55869023-92983900-5b7d-11e9-9dd3-8d5e534c790c.PNG)

I can traverse the file tree using FM, but the images are not there.

NB It was working fine. I had changed a few paths around (experimenting). Thumbnails broke. I changed the paths back to what is shown here, but images remained broken - so am I seeing a cache? Have tried cache:clear and view:clear with no effect.

Where is the application?
/path/htdocs/application

Uploads are handled separately.

Where are the images? Hosted on a different subdomain "assignments.example.com" in the folder tree:
/path/htdocs/assignments/ #the subdomain root
/path/htdocs/assignments/uploads #the tree where the images are

file-manager.php
```
    'middleware' => ['web','fm-acl'],
    'acl' => true,
    'aclHideFromFM' => true,
    'aclStrategy'   => 'whitelist',
    'aclRepository' => \App\Http\FileManagerUserACL::class,
```

FileManagerUserACL.php (only admin -me- can access at the moment but planning to have dynamic ACL per user) 
```
   public function getRules(): array
    {
        if (\Auth::id() === 1) {
            return [
                ['disk' => 'Assignments', 'path' => '*', 'access' => 1],
            ];
        }
        
        return [
            // todo
        ];
    }
```

filesystems.php
```
'disks' => [

        ...

        'Assignments' => [
            'driver' => 'local',
            'root' => '/path/htdocs/assignments/uploads/',
            'url' => 'assignments.example.com/uploads/',
            'visibility' => 'public',
        ],

       ...

    ],
```

**Comment by alexusmai** [comment]
Hi, 
I don't know why this happened ... but you can try:

First set cache settings

```
/**
     * Image cache ( Intervention Image Cache )
     * set null, 0 - if you don't need cache (default)
     * if you want use cache - set the number of minutes for which the value should be cached
     */
    'cache' => null,
```

Clean cache folder - storage/framework/cache/data

If you changed the application code, you may need to reinstall the application.

The [InterventionImage](http://image.intervention.io/) library is responsible for the pictures.
Check if it works normally.. in your environment.

About the connection folder. I would advise you to try to make a symlink to the folder you need.

**Comment by guevagio** [comment]
Hi,
I was getting the same behavior, 200 response but broken images. After spending some time comparing my code with a working backup, I found that one of my routes file had a blank space before the opening PHP tag in the first line.

Once removed the thumbnails worked again. If you have the same problem, try to look for blank leading spaces in your PHP tags, that may fix the issue.
