### ISSUE TITLE
route list

### ISSUE THREAD

**Issue by mdhosseini** [alexusmai/laravel-file-manager#36]
i have some question about this file manager
1- what's this file manage route?
2- how can i disable show file manager if have no access (for example access to show in acl)
3-how can i disable create new file (not folder)
4- how can i access to crate some type of file like txt (no php or js)
5-how can i change upload file types

please help me

**Comment by alexusmai** [comment]
Hi.
1. I don't understand what do you mean... If you want to see routes - you can use command - 
```
php artisan route:list
```

all file-manager routes hase names - fm.initialize, fm.content, fm.tree, ...

2. ACL - you can use only for files and folders, show/hide them in FM. If you want to hide FM - you can do it in your application using user roles or ... and restrict access using middleware.

3, 4, 5 - package doesn't have functional for it.

**Comment by mdhosseini** [comment]
i need file manager rout list for my ACL
for example upload route or show file manage route and other

for question 2  (use acl for show filemanager and other) can you tell me more info?
