### ISSUE TITLE
change filename when upload 

### ISSUE THREAD

**Issue by prg-hussam** [alexusmai/laravel-file-manager#37]
how i can generate new name for file when upload

**Comment by xuweisen** [comment]
Yes, I also looking for how to generate new name when upload.
And also is it possible to change the "path" value on the properties modal into url path of the file?

Thanks

**Comment by alexusmai** [comment]
Hi, the package has no functionality for renaming when uploading a file.
Maybe you try to rename the file when it is uploaded to the server? For it you can use events - [FilesUploaded](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)

**Comment by xuweisen** [comment]
> Hi, the package has no functionality for renaming when uploading a file.
> Maybe you try to rename the file when it is uploaded to the server? For it you can use events - [FilesUploaded](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)

Noted, Thanks :)

**Comment by manhquan01** [comment]
Hi Alexusma, i want change filename by my rule while user rename file or folder. Can you help me ?

**Comment by mindaugasva** [comment]
> Hi Alexusma, i want change filename by my rule while user rename file or folder. Can you help me ?

You have to use Events. For example:
```
Event::listen('Alexusmai\LaravelFileManager\Events\Rename',
            function ($event) {

                $_name = File::name($event->newName());
                if($_name[0] == '.'){
                    throw new Exception('Name error.');
                }

                if($event->type() === 'file'){
                    $extension = File::extension($event->oldName());
                    if(filemanager_extention_allowed($extension)){
                        throw new Exception('The '.$event->newName().' must be a file of type: '.implode(',', config('file-manager.allowFileTypes')).'.');
                    }
                    $newName = Str::slug($_name, '-') . '.' . $extension;
                    $dirname = File::dirname($event->newName());
                    if($dirname != '.') $newName = $dirname . '/' . $newName;
                    request()->merge(['newName' => $newName]);
                } else {
                    request()->merge(['newName' => Str::slug($event->newName(), '-')]);
                }
            }
        );
```
If your new filename start at '.' (dot) - deny
If your new filename extention is not in allowed (in config) - deny
And last fix - I change filename/dirname to slug (without unallowed symbols)

**Comment by bhavesh-786** [comment]
Hello Alexusma,
