### ISSUE TITLE
Show real path of the file/image

### ISSUE THREAD

**Issue by xuweisen** [alexusmai/laravel-file-manager#38]
<img width="1226" alt="Screen Shot 2019-04-19 at 10 20 52 AM" src="https://user-images.githubusercontent.com/13136251/56401772-1690a600-628d-11e9-8369-d528c01c5328.png">

Hi, Is it possible to change the value of the path on the modal into real path of the file/image?
I tried to open the js file, and it shown e.selectedItem.path. I don't know where i can set/change this variable value.

The real path should be like https://domain.com/images/upload/0a8bbd26b03ed2b619ca12fe8e4b2e2c.jpg

Thanks

**Comment by alexusmai** [comment]
I can add a method that will return the URL of the file in the file properties list. 
This method exists, he gives url when working with text editors. 
But it will return the link according to your settings - more about it - [File URLs](https://laravel.com/docs/filesystem#retrieving-files)

// filesystems.php
```
'disks' => [
     'images' => [
            'driver' => 'local',
            'root' => public_path('images'),
            'url' => env('APP_URL').'/images',  // !!! return URL !!!
        ],
]
```

**Comment by ashfaq1994** [comment]
When i integrated with summernote. When i selected Image and in console, I'm getting 404 error. Due to the path. Please fix it

https://www.awesomescreenshot.com/image/3983769/d3c0dc5f2e586e4c4d0b2a7d920dca0f

**Comment by alexusmai** [comment]
> When i integrated with summernote. When i selected Image and in console, I'm getting 404 error. Due to the path. Please fix it

Hi. 
You have a problem with laravel filesystem settings. If you use storage folder - don't forget to create a symbolic link - [docs](https://laravel.com/docs/filesystem#configuration)

**Comment by ashfaq1994** [comment]
First of all, thank you for such a great package. Thanks again for the reply. Please tell me how to change the storage directory.  
Where should i change it?

**Comment by alexusmai** [comment]
Setttings example:

config/filesystems.php

```
'disks' => [
        'storage' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),  // storage/app/public
            'url' => '/storage',   // create symbolic link !!! - php artisan storage:link
        ],

        // you can use public path - for example for the pictures that are used in the article.
        'images' => [
            'driver' => 'local',
            'root' => public_path('images'),  // public/images
            'url' => '/images',
        ],
    ],
```

add these disks to the file manager - config/file-manager.php

**Comment by ashfaq1994** [comment]
I have created php artisan storage:link and same above settings for filesystems.php stills same 404 ajax error.

**Comment by alexusmai** [comment]
If you put some file (image.png) to folder - storage/app/public and then go to address http://__your.url__/storage/image.png - you will see this image, if not - you have problems with configuration - symbolic link or settings or environtments...

P.S I see you use localhost:8000 (port number) - try to add this port to 'url':

```
'storage' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => 'localhost:8000/storage',
        ],
```

**Comment by ashfaq1994** [comment]
Same error with settings
```

   'disks' => [
        'storage' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),  // storage/app/public
            'url' => 'localhost:8000/storage',   // create symbolic link !!! - php artisan storage:link
        ],

        // you can use public path - for example for the pictures that are used in the article.
        'images' => [
            'driver' => 'local',
            'root' => public_path('images'),  // public/images
            'url' => '/images',
        ],
    ],
```

**Comment by ashfaq1994** [comment]
I have changed this .env file too `APP_URL=http://localhost:8000`

**Comment by alexusmai** [comment]
> If you put some file (image.png) to folder - storage/app/public and then go to address http://**your.url**/storage/image.png - you will see this image, if not - you have problems with configuration - symbolic link or settings or environtments...

Do you see image?

**Comment by ashfaq1994** [comment]
Okay got it.

Thank you very much

**Comment by ashfaq1994** [comment]
After changing to a virtual host. Now I'm getting a new error. Config not found!  the same configuration i did as you told me.

**Comment by ashfaq1994** [comment]
Finally working. Thanks for the support.

**Comment by ashfaq1994** [comment]
When i have a SummerNote and Standalone button same page. when inserting an image via SummerNote working fine then i use Standalone for different input field that time still appending image to SummerNote . How to fix this?

**Comment by ashfaq1994** [comment]
Please reply?

**Comment by alexusmai** [comment]
Hi, see example:

```
<div class="container">
    <div id="summernote"></div>
</div>

<div class="container">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="image_input1">Image1</label>
            <div class="input-group">
                <input type="text" id="image_input1" class="form-control" name="image1">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-image1">Select</button>
                </div>
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="image_input2">Image2</label>
            <div class="input-group">
                <input type="text" id="image_input2" class="form-control" name="image2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-image2">Select</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
  $(document).ready(function(){
    // File manager button (image icon)
    const FMButton = function(context) {
      const ui = $.summernote.ui;
      const button = ui.button({
        contents: '<i class="note-icon-picture"></i> ',
        tooltip: 'File Manager',
        click: function() {
          selectedInput = 'editor';

          window.open('/file-manager/summernote', 'fm', 'width=1400,height=800');
        }
      });
      return button.render();
    };

    $('#summernote').summernote({
      toolbar: [
        // [groupName, [list of button]]
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['font', ['strikethrough', 'superscript', 'subscript']],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        ['fm-button', ['fm']],
      ],
      buttons: {
        fm: FMButton
      }
    });

    // first button
    document.getElementById('button-image1').addEventListener('click', (event) => {
      event.preventDefault();

      selectedInput = 'image_input1';

      window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
    });

    // second button
    document.getElementById('button-image2').addEventListener('click', (event) => {
      event.preventDefault();

      selectedInput = 'image_input2';

      window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
    });
  });

  // input
  let selectedInput = '';

  // set file link
  function fmSetLink(url) {
    if (selectedInput === 'editor') {
      $('#summernote').summernote('insertImage', url);
    } else {
      document.getElementById(selectedInput).value = url;
    }
  }
</script>
```

**Comment by ashfaq1994** [comment]
> Hi, see example:
> 
> ```
> <div class="container">
>     <div id="summernote"></div>
> </div>
> 
> <div class="container">
>     <div class="form-row">
>         <div class="form-group col-md-6">
>             <label for="image_input1">Image1</label>
>             <div class="input-group">
>                 <input type="text" id="image_input1" class="form-control" name="image1">
>                 <div class="input-group-append">
>                     <button class="btn btn-outline-secondary" type="button" id="button-image1">Select</button>
>                 </div>
>             </div>
>         </div>
>         <div class="form-group col-md-6">
>             <label for="image_input2">Image2</label>
>             <div class="input-group">
>                 <input type="text" id="image_input2" class="form-control" name="image2">
>                 <div class="input-group-append">
>                     <button class="btn btn-outline-secondary" type="button" id="button-image2">Select</button>
>                 </div>
>             </div>
>         </div>
>     </div>
> </div>
> 
> 
> <script>
>   $(document).ready(function(){
>     // File manager button (image icon)
>     const FMButton = function(context) {
>       const ui = $.summernote.ui;
>       const button = ui.button({
>         contents: '<i class="note-icon-picture"></i> ',
>         tooltip: 'File Manager',
>         click: function() {
>           selectedInput = 'editor';
> 
>           window.open('/file-manager/summernote', 'fm', 'width=1400,height=800');
>         }
>       });
>       return button.render();
>     };
> 
>     $('#summernote').summernote({
>       toolbar: [
>         // [groupName, [list of button]]
>         ['style', ['bold', 'italic', 'underline', 'clear']],
>         ['font', ['strikethrough', 'superscript', 'subscript']],
>         ['fontsize', ['fontsize']],
>         ['color', ['color']],
>         ['para', ['ul', 'ol', 'paragraph']],
>         ['height', ['height']],
>         ['fm-button', ['fm']],
>       ],
>       buttons: {
>         fm: FMButton
>       }
>     });
> 
>     // first button
>     document.getElementById('button-image1').addEventListener('click', (event) => {
>       event.preventDefault();
> 
>       selectedInput = 'image_input1';
> 
>       window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
>     });
> 
>     // second button
>     document.getElementById('button-image2').addEventListener('click', (event) => {
>       event.preventDefault();
> 
>       selectedInput = 'image_input2';
> 
>       window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
>     });
>   });
> 
>   // input
>   let selectedInput = '';
> 
>   // set file link
>   function fmSetLink(url) {
>     if (selectedInput === 'editor') {
>       $('#summernote').summernote('insertImage', url);
>     } else {
>       document.getElementById(selectedInput).value = url;
>     }
>   }
> </script>
> ```

Thanks. But when i upload in shared hosting. Image not coming? How to fix it?

**Comment by alexusmai** [comment]
I think the problem in shared hosting...
