### ISSUE TITLE
Auto Select Path Dynamically

### ISSUE THREAD

**Issue by puremana** [alexusmai/laravel-file-manager#39]
Hi,

Similar to https://github.com/alexusmai/laravel-file-manager/issues/21 I was wondering if it is possible to dynamically change into a path based on URL parameters or something similar.

For example, if my file path config is set to public folder, and my public folder contains 2 folders, 'A' and 'B', whether it would be possible to go to http://site-name.com/your-url?path=A to directly go to the A folder. And if there was another folder inside A, http://site-name.com/your-url?path=A/another-folder

I have not seen this functionality to be able to be set dynamically in the docs but please let me know if this is already possible

Thank you for creating this nice looking file manager for Laravel!

**Comment by alexusmai** [comment]
Hi.

I added this feature - and updated the documentation - [configuration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md)

Upgrading to a new version [upgrade 2.3](https://github.com/alexusmai/laravel-file-manager#in-new-version-23)

**Comment by puremana** [comment]
Thank you for updating so quickly! However, I am having some trouble updating to this new version. I updated to 2.3 using composer and added the leftPath and rightPath variables to the file-manager config file. 

When I now run the file manager page, it works the same as before, no errors but the selecting path functionality does not work.

Then, after I run this command to publish the new JS and CSS
`php artisan vendor:publish --tag=fm-assets --force`
I get a network error on the file manager

![image](https://user-images.githubusercontent.com/2869411/57043626-404dc200-6cbc-11e9-845f-56ce325e00a2.png)

This happens despite the URL

Here are the console errors
![image](https://user-images.githubusercontent.com/2869411/57043676-5f4c5400-6cbc-11e9-9d8a-525d1c04cf77.png)

Using Chrome Version 74.0.3729.108, Laravel Version 5.8.15
Have tried clearing config / views

**Comment by alexusmai** [comment]
Hi, sorry it's my mistake.. please update package and pre-compiled js

**Comment by puremana** [comment]
Thank you, everything is up and running!
