### ISSUE TITLE
Не отображается файловый менеджер

### ISSUE THREAD

**Issue by Vladislav009** [alexusmai/laravel-file-manager#4]
Здравствуйте, прошелся по каждому пункту в инструкции по установке, на варианте с фронтэндом использовал 1 вариант. 
![image](https://user-images.githubusercontent.com/36544567/44094837-aa068aea-9ff0-11e8-9d13-9b5d1c3ce4d7.png)

**Comment by alexusmai** [comment]
Первый вариант нужен для того чтобы встроить файловый менеджер в свое Vue приложение, и дальнейшая настройка частично описана [тут](https://github.com/alexusmai/vue-laravel-file-manager)

Если нужен только файловый менеджер - используйте второй вариант. Он проще и не требует знаний Vue. Кстати 5-ый пункт настроек написан для 2-го варианта..
