### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by digitaliza** [alexusmai/laravel-file-manager#40]
Hi i'm trying to use your package, but when i open the editor view,i receive error with internet.
when i open file manager himself, another error
see:

![image](https://user-images.githubusercontent.com/43499392/57157337-cf3f0500-6db6-11e9-802b-8b0ca182f6d2.png)

![image](https://user-images.githubusercontent.com/43499392/57157536-568c7880-6db7-11e9-84fc-883c09f053f9.png)

my disk config:
`
![image](https://user-images.githubusercontent.com/43499392/57157812-1b3e7980-6db8-11e9-8cb7-b342c8bbbe5b.png)

my view with tinymce and assets for file-manager

`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
    <script src="{{asset('dependencias/tinymce/js/tinymce/tinymce.min.js')}}"></script>
    <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script> `

` ,

            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media',
            relative_urls: false,
            file_browser_callback: function(field_name, url, type, win) {
                tinyMCE.activeEditor.windowManager.open({
                    file: '/file-manager/tinymce',
                    title: 'Laravel File Manager',
                    width: window.innerWidth * 0.8,
                    height: window.innerHeight * 0.8,
                    resizable: 'yes',
                    close_previous: 'no',
                }, {
                    setUrl: function(url) {
                        win.document.getElementById(field_name).value = url;
                    },
                });
            },
        });`

**Comment by alexusmai** [comment]
Hi, please update package, and re-publish compiled js

```
php artisan vendor:publish --tag=fm-assets --force
```

**Comment by digitaliza** [comment]
Thank you, it worked.
Thank you also for the quick response.
We appreciate your support!
