### ISSUE TITLE
FTP File System not working

### ISSUE THREAD

**Issue by jpcodeforit** [alexusmai/laravel-file-manager#41]
I have installed laravel 5.8 and latest laravel file manager. and in my file system i am using ftp connection.
I have successfully able to list directories from ftp connection and also image download working fine.
when i try to select or insert image into summernote i got following error.

> 500 - This driver does not support retrieving URLs.

**Comment by alexusmai** [comment]
Hi.
Yes, ftp driver doesn't return the URL. This method works with - local driver and s3, rackspace - [File URLs](https://laravel.com/docs/filesystem#file-urls).

**Comment by jpcodeforit** [comment]
@alexusmai .thanks for the quick reply.I have tried in dropxbox .there also i got same issue 

> 500 - This driver does not support retrieving URLs.
> 500 - This driver does not support retrieving URLs.

**Comment by alexusmai** [comment]
> is there any chance to fix for dropbox

The problem isn't in the Dropbox driver - the problem is that Dropbox does not support this functionality.

**Comment by jpcodeforit** [comment]
@alexusmai .Thanks for the reply .

**Comment by 95moja71** [comment]
i use ftp for main file manager all images of products store it , how i can get  url with file name ?

        'seller' => [

            'driver'   => 'ftp',
            'host'     => '*********',
            'username' => '********',
            'password' => 'nH31x#18TUw-Tx',
            'passive'  => true,
            'timeout'  => 30,
            'root'=>'public_html',
            'url'=>'http://cdn.******.net/'
        ],
