### ISSUE TITLE
Download size limit images, files

### ISSUE THREAD

**Issue by sergey89d** [alexusmai/laravel-file-manager#42]
Is it possible to limit the loading of images or files to the desired size? If not, will it be in the future?

**Comment by sergey89d** [comment]
Можно ответить на русском)

**Comment by alexusmai** [comment]
Привет.
Сейчас такого функционала нет. Добавить в принципе можно, как будет время сделаю.
Вопрос не закрывай.. чтоб я не забыл, как будет готово я сам закрою.

**Comment by sergey89d** [comment]
Я вот еще придумал, еще бы ограничить загрузку в папку, если папка уже n-нного размера.
Спасибо!

**Comment by alexusmai** [comment]
Добавил параметры для ограничения размера загружаемых файлов, также добавил возможность указать разрешенные типы файлов для загрузки.

**Comment by sergey89d** [comment]
Круто! Спаcибо)
