### ISSUE TITLE
Select multiple images and insert

### ISSUE THREAD

**Issue by ramonpego** [alexusmai/laravel-file-manager#43]
Hi, i'm using your package and loveing it, 
but its a interessing feature, if i had many images to insert, its will become a exaustive, every image, i have to open file-manager (if its like myself using s3, its will  become more slowly) and insert them.
If i can select all and insert it will be very helpfull

best reggards.

**Comment by alexusmai** [comment]
Hi, thank you.
I can make a multi-select in the file manager, but the problem is how to transfer it to a text editor. Ckeditor, Tinymce,..  usually providing a selection of one image at a time

**Comment by ramonpego** [comment]
make sense, so, it's out of your hands, thank you for the return i appreciate that.
