### ISSUE TITLE
Как верно настроить ACL на S3

### ISSUE THREAD

**Issue by sergey89d** [alexusmai/laravel-file-manager#44]
Вечер добрый. 
Сразу к сути, у меня на s3 под каждого пользователя создается в корне корзины (bucket) своя папка с подпапками, скажем ivanov_1 и ее подпапки images, filemanager, articles, .... Как правильно настроить UsersACLRepository, чтобы при загрузке чего либо в редакторе, пользователь видел только одну подпапку в своей главной папке? И второй вопрос, зачем метод ```getUserID``` переопределяется в UsersACLRepository, можно вместо id что-то отдавать другое? Спасибо

Сам UsersACLRespository
```php
<?php

namespace App\Repository;

use Alexusmai\LaravelFileManager\Services\ACLService\ACLRepository;

/**
 * Class UsersACLRepository
 * @package App\Repository
 */
class UsersACLRepository implements ACLRepository
{
    /**
     * Get user ID
     *
     * @return mixed
     */
    public function getUserID()
    {
        return \Auth::user()->id;
    }

    /**
     * Get ACL rules list for user
     *
     * @return array
     */
    public function getRules(): array
    {
       $dir = \Auth::user()->name . '_' .\Auth::user()->id;
        return [
            ['disk' => 's3', 'path' => $dir.'/fm/*', 'access' => 2],
        ];
    }
}
```
Сам конфиг fm
```php
<?php

return [

    /**
     * list of disk names that you want to use
     * (from config/filesystems)
     */
    'diskList'  => ['s3'],

    /**
     * Default disk for left manager
     * null - auto select the first disk in the disk list
     */
    'leftDisk'  => null,

    /**
     * Default disk for right manager
     * null - auto select the first disk in the disk list
     */
    'rightDisk' => null,

    /**
	 * Default path for left manager
	 * null - root directory
	 */
	'leftPath'  => null,

	/**
	 * Default path for right manager
	 * null - root directory
	 */
	'rightPath' => null,

    /**
     * Image cache ( Intervention Image Cache )
     * set null, 0 - if you don't need cache (default)
     * if you want use cache - set the number of minutes for which the value should be cached
     */
    'cache' => null,

    /**
     * File manager modules configuration
     * 1 - only one file manager window
     * 2 - one file manager window with directories tree module
     * 3 - two file manager windows
     */
    'windowsConfig' => 2,

    /***************************************************************************
     * Middleware
     * Add your middleware name to array -> ['web', 'auth', 'admin']
     * !!!! RESTRICT ACCESS FOR NON ADMIN USERS !!!!
     *
     * !!! For using ACL - add 'fm-acl' to array !!! ['web', 'fm-acl']
     */
    'middleware' => ['web', 'auth', 'fm-acl'],

    /***************************************************************************
     * ACL mechanism ON/OFF
     *
     * default - false(OFF)
     */
    'acl' => true,

    /**
     * Hide files and folders from file-manager if user doesn't have access
     * ACL access level = 0
     */
    'aclHideFromFM' => true,

    /**
     * ACL strategy
     *
     * blacklist - Allow everything(access - 2 - r/w) that is not forbidden by the ACL rules list
     *
     * whitelist - Deny anything(access - 0 - deny), that not allowed by the ACL rules list
     */
    'aclStrategy'   => 'blacklist',

    /**
     * ACL rules repository
     *
     * default - config file(ConfigACLRepository)
     */
    'aclRepository' => \App\Repository\UsersACLRepository::class,
    //'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\ConfigACLRepository::class,
    //'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\DBACLRepository::class,

    /**
     * ACL rules list - used for default repository
     *
     * 1 it's user ID
     * null - for not authenticated user
     *
     * 'disk' => 'disk-name'
     *
     * 'path' => 'folder-name'
     * 'path' => 'folder1*' - select folder1, folder12, folder1/sub-folder, ...
     * 'path' => 'folder2/*' - select folder2/sub-folder,... but not select folder2 !!!
     * 'path' => 'folder-name/file-name.jpg'
     * 'path' => 'folder-name/*.jpg'
     *
     * * - wildcard
     *
     * access: 0 - deny, 1 - read, 2 - read/write
     */
    'aclRules'      => [
        null => [
            ['disk' => 'public', 'path' => '*', 'access' => 0]
        ],
       /* 1 => [
        	['disk' => 's3', 'path' => '*', 'access' => 2]
        ]*/
    ],

    /**
     * ACL Rules cache
     *
     * null or value in minutes
     */
    'aclRulesCache' => null,
];
```

**Comment by alexusmai** [comment]
Можно использовать этот [пример](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md#example-2)

Он использует стратегию "Белый список" - ЗАПРЕТИТЬ ВСЕ!!!, что не разрешено в этом списке. Это важно! Поэтому до нужной папки нужно открыть доступ

```
'aclStrategy'   => 'whitelist',
```

Правила соответственно будут примерно такие:

```
public function getRules(): array
    {
        $dir = \Auth::user()->name . '_' .\Auth::user()->id;

        return [
            // открываем доступ на чтение к корню диска
            ['disk' => 's3', 'path' => '/', 'access' => 1],
            // открываем доступ к пользовательской папке - на чтение
            ['disk' => 's3', 'path' => $dir, 'access' => 1],
            // также даем доступ на чтение(чтоб не могли удалить или переименовать) на нужную папку
            ['disk' => 's3', 'path' => $dir. '/fm' , 'access' => 1],
            // в нужной папке разрешаем чтение и запись на все файлы и папки
            ['disk' => 's3', 'path' =>  $dir. '/fm/*', 'access' => 2],
        ];
    }
```



> И второй вопрос, зачем метод `getUserID` переопределяется в UsersACLRepository, можно вместо id что-то отдавать другое?

Он не переопределяется.. ACLRepository - это интерфейс, то есть метод не имеет реализации, и нам нужно ее написать. А сам метод нужен для кэширования правил, чтобы кэш помечать... а отдавать может что угодно.. может вместо id какой-то другой столбец используется.. UUID какой-нибудь... Короче говоря для каждого пользователя должен возвращать уникальное значение.

**Comment by sergey89d** [comment]
А можно как-то схитрить что ли)) Чтобы при открытии загрузчика файлов, то по умолчанию открывалась папка user_dir / fm / и туда смотрел загрузчик сразу ? А то  сейчас же, надо выбрать папку, потом еще выбрать подпапку, не особо удобно
![image](https://user-images.githubusercontent.com/21147339/58513859-1ac3b380-81a9-11e9-843d-ee4aa0edfb57.png)

**Comment by sergey89d** [comment]
Еще и ошибку ловлю при создании
Немного лог трейса
```
Undefined index: path at /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/Traits/ContentTrait.php:203)
[stacktrace]
#0 /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/Traits/ContentTrait.php(203): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/home/admin/web...', 203, Array)
#1 [internal function]: Alexusmai\\LaravelFileManager\\FileManager->Alexusmai\\LaravelFileManager\\Traits\\{closure}(Array)
#2 /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/Traits/ContentTrait.php(206): array_map(Object(Closure), Array)
#3 /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/Traits/ContentTrait.php(133): Alexusmai\\LaravelFileManager\\FileManager->aclFilter('s3', Array)
#4 /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/FileManager.php(347): Alexusmai\\LaravelFileManager\\FileManager->directoryProperties('s3', 'zaykov_ia_2/fm/...')
#5 /home/admin/web/sites.ru/public_html/vendor/alexusmai/laravel-file-manager/src/Controllers/FileManagerController.php(267): Alexusmai\\LaravelFileManager\\FileManager->createDirectory('s3', 'zaykov_ia_2/fm', '89778')```

**Comment by alexusmai** [comment]
> А можно как-то схитрить что ли)) Чтобы при открытии загрузчика файлов, то по умолчанию открывалась папка user_dir / fm / и туда смотрел загрузчик сразу ?

Можно попробовать такой вариант - [документация](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/configuration.md#you-can-set-default-disk-and-default-path)

По ошибке - ругается на добавление уровня доступа(acl) в перечень свойств элемента.. у меня такой ошибки нет, была похожая, когда забыл в список middleware добавить fm-acl и пробовал создавать папку там где не было доступа на запись

**Comment by sergey89d** [comment]
@alexusmai на счёт папки по умолчанию спасибо.
На счёт ошибки, у меня выше в конфиге прописано в миддлвеар fm-acl, но ошибка есть

**Comment by alexusmai** [comment]
Выложи свой класс для ACL и структуру папок с которой нужно работать, я как будет время проверю у себя.. так как у меня такой ошибки нет.

**Comment by sergey89d** [comment]
ACL
```php
<?php

namespace App\Repository;

use Alexusmai\LaravelFileManager\Services\ACLService\ACLRepository;

/**
 * Class UsersACLRepository
 * @package App\Repository
 */
class UsersACLRepository implements ACLRepository
{

    /**
     * Get user ID
     *
     * @return mixed
     */
    public function getUserID()
    {
        return \Auth::user()->id;
    }

    /**
     * Get ACL rules list for user
     *
     * @return array
     */
    public function getRules(): array
    {
        if (\Auth::user()->isAdmin()) {
            return [
                ['disk' => 's3', 'path' => '*', 'access' => 2],
            ];
        }
        
        return [
            // открываем доступ на чтение к корню диска
            ['disk' => 's3', 'path' => '/', 'access' => 1],
            // открываем доступ к пользовательской папке - на чтение
            ['disk' => 's3', 'path' => \Auth::user()->user_dir, 'access' => 1],
            // также даем доступ на чтение(чтоб не могли удалить или переименовать) на нужную папку
            ['disk' => 's3', 'path' => \Auth::user()->user_dir. '/fm', 'access' => 1],
            // в нужной папке разрешаем чтение и запись на все файлы и папки
            ['disk' => 's3', 'path' => \Auth::user()->user_dir. '/fm/*', 'access' => 2],
        ];
    }
}
```
И структура такая, в корне s3 создаются папки при регистрации человека, берется Имя и ID
![image](https://user-images.githubusercontent.com/21147339/58629520-5e233c80-82e5-11e9-996b-9925fad1ef57.png)
![image](https://user-images.githubusercontent.com/21147339/58629537-65e2e100-82e5-11e9-9e97-2a380daabab5.png)

**Comment by alexusmai** [comment]
Правила просмотрел, проверил.. у меня для теста такие же примерно.. все работает..

Есть единственный момент в этой конструкции:

```
public function getUserID()
{
        return \Auth::user()->id;
 }
```

Если пользователя нет, например у меня для тестов есть доступ всем - и незалогиненым пользователям тоже.. то тут будет ошибка.. так как пользователя нет.
Я использую такой вариант:

```
return \Auth::id();
```

Если нет пользователя то возвращает null - то есть гость, и можно для них прописать нужные правила.

Хотя у тебя вроде прописан auth middleware... но может тестишь без него..

Еще как вариант проверить что возвращает \Auth::user()->user_dir - там должна быть одна папка - например marina_19 а не folder/sub-folder/marina_19

Ну и проверить все эти правила на обычном локальном диске, а не на S3, т.к. я на S3 не проверял.. нет у меня его..

**Comment by sergey89d** [comment]
> return \Auth::id();
попробую этот вариант

> Еще как вариант проверить что возвращает \Auth::user()->user_dir - там должна быть одна папка - например marina_19 а не folder/sub-folder/marina_19
Здесь всё нормально, там возвращается только название папки без каких путей, мутаций и прочего.

> Ну и проверить все эти правила на обычном локальном диске, а не на S3, т.к. я на S3 не проверял.. нет у меня его..
Проверю и отпишусь

**Comment by sergey89d** [comment]
День добрый. Переключил я на public диск и создание папки без ошибок происходит, на амазоне с ошибкой **Undefined index: path**

**Comment by sergey89d** [comment]
@alexusmai надо фиксить)

**Comment by alexusmai** [comment]
А S3 не работает как нужно именно с включенным ACL?

**Comment by sergey89d** [comment]
Да, именно s3 с ACL

**Comment by alexusmai** [comment]
Привет, попробуй новую версию, там пофиксил проблему с S3 (драйвер для S3 не отдает metadata для папок)

**Comment by sergey89d** [comment]
Отлично. Попробую, отпишусь)

**Comment by sergey89d** [comment]
Ошибки нету при создании директории и загрузке файлов на s3. Спасибо!
