### ISSUE TITLE
Редирект на страницу авторизации

### ISSUE THREAD

**Issue by Siarhei-Sudakou** [alexusmai/laravel-file-manager#46]
Постоянный редирект на страницу авторизации при попытке просмотреть изображение или tnumbnail, или скачать.

'middleware' => ['auth:administrator-api'],

**Comment by alexusmai** [comment]
Попробуйте новую версию, я добавил функцию для загрузки изображений и превью с передачей заголовка для авторизации.

**Comment by Siarhei-Sudakou** [comment]
Огромное спасибо! Остался только вопрос с обновлением токена. https://github.com/alexusmai/vue-laravel-file-manager/issues/22
