### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by alfin87aa** [alexusmai/laravel-file-manager#47]
Hi,

I tried to using with Google Cloud Storage but i get some error please check my result after i tried some test in bellow, thanks a lot for your help.

- Upload File (Working)
- Crop Image (Working)
- Delete File (Working)
- Rename File (Working)
- Create Folder (Working)
- Open Folder (Not Working 422 - Not found!)
- Delete Folder (Not Working Just notification success but the folder still there)

**Comment by alexusmai** [comment]
Hi.
I don't have Google Cloud Storage for test..

**Comment by duongductrong** [comment]
@alfin87aa 
Hi, can u show me your setup in config filesystems.php? 
I'm working on it but don't know how to configure it properly
