### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by giogiosw** [alexusmai/laravel-file-manager#48]
Hi
Hello
I have this problem with the English language, I get the following error "file-manager :: response.aclError" how can I add it to the language?
thank you

**Comment by alexusmai** [comment]
Hi.
It's strange, this phrase translated.. [link](https://github.com/alexusmai/laravel-file-manager/blob/a5eef4f8c5d4f69fdfeb28138116ef9561063518/resources/lang/en/response.php#L27)

If you want to overwrite it, publish:

```
php artisan vendor:publish --tag=fm-lang
```
