### ISSUE TITLE
Is there a way to set Grid as the default display style?

### ISSUE THREAD

**Issue by minhtu-cloudtek** [alexusmai/laravel-file-manager#49]
Hi Mr. Dev Master,

Is there a way for me to set `Grid` as the default display style, instead of `List`?

**Comment by alexusmai** [comment]
Hi.
The package doesn't have functions for it.

**Comment by ukits** [comment]
I also need this function.

**Comment by vsmartcode** [comment]
you can set in tag script
`fm.$store.commit("fm/".concat(fm.$store.state.fm.activeManager, "/setView"), 'grid')`
