### ISSUE TITLE
Static initialize on root

### ISSUE THREAD

**Issue by burdacz** [alexusmai/laravel-file-manager#50]
Hi, we used your file manager on localhost and it is perfect! But when we tried to push it on server your package is trying to initialize on root like: rooturl.cz/file-manager/initialize but our application is not on root but on rooturl.cz/app/... so we needed to add htaccess file on root so we redirect that. It would be nice to have some config for prefixes in url. Thank you

**Comment by alexusmai** [comment]
Hi.
You can use [vue package](https://github.com/alexusmai/vue-laravel-file-manager) where you can change some default settings like baseURL
