### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by olcy** [alexusmai/laravel-file-manager#53]
Hi,

Sorry for this post i know it's a configuration issue but i have 2 error 500.
https://gyazo.com/6a4f114b3b5d89e7d2ef7eaeef341671

This works fine in local but not on production.

The production machine is setup with debian 9 & nginx.

I have tried to fix permissions folders and files without success.

Do you have any idea ?

Thank's in advance for you're help.

**Comment by alexusmai** [comment]
Hi,

What is in the logs?

**Comment by olcy** [comment]
Hi, 

Thank's for the reply, if i use the fm button i have this in log : 

`==> /var/log/nginx/access.log <==
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:15 +0200] "GET /gestion HTTP/2.0" 200 4426 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:16 +0200] "GET /assets/backend/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/2.0" 200 77391 "https://domain.com/assets/backend/css/font-awesome.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:18 +0200] "GET /gestionnaire-de-medias HTTP/2.0" 200 2931 "https://domain.com/gestion" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:18 +0200] "GET /file-manager/fm-button HTTP/2.0" 200 1430 "https://domain.com/gestionnaire-de-medias" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:18 +0200] "GET /file-manager/initialize HTTP/2.0" 200 947 "https://domain.com/file-manager/fm-button" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:18 +0200] "GET /file-manager/content?disk=public HTTP/2.0" 500 732 "https://domain.com/file-manager/fm-button" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:43:18 +0200] "GET /file-manager/tree?disk=public HTTP/2.0" 500 734 "https://domain.com/file-manager/fm-button" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"`

If i use tinymce : 
`==> /var/log/nginx/access.log <==
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:48:02 +0200] "GET /file-manager/tinymce HTTP/2.0" 200 1647 "https://domain.com/gestion/wiki/edit/43" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:48:02 +0200] "GET /file-manager/initialize HTTP/2.0" 200 950 "https://domain.com/file-manager/tinymce" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:48:02 +0200] "GET /file-manager/content?disk=public HTTP/2.0" 500 739 "https://domain.com/file-manager/tinymce" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
xxx.xxx.xxx.xxx - - [03/Jul/2019:19:48:02 +0200] "GET /file-manager/tree?disk=public HTTP/2.0" 500 729 "https://domain.com/file-manager/tinymce" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"`

I have no error in error.log and no error in laravel.log

Thnk's in advance for you're help 👍

**Comment by alexusmai** [comment]
Maybe you forgot to create symbolic link (if your disk use storage/app folder) - [docs](https://laravel.com/docs/filesystem#the-public-disk)

Folders permissions - something like this:

```
find /var/www/your_folder_here -type f -exec chmod 644 {} \;

find /var/www/your_folder_here -type d -exec chmod 755 {} \;

find /var/www/your_folder_here/storage/* -type d -exec chmod 775 {} \;

find /var/www/your_folder_here/bootstrap/cache -type d -exec chmod 775 {} \;
```

Show your config - filesystems.php ('disks' array)

**Comment by olcy** [comment]
I have tried you're solutions for permissions but it's dosn't help.

This my filesystems.php

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => env('FILESYSTEM_CLOUD', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "sftp", "s3", "rackspace"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

    ],

];
`
Thank's for you're time !

**Comment by alexusmai** [comment]
Try to check your filesystems settings without using LFM, use tinker:

```
php artisan tinker

// try to execute command - the list of folders in the root directory of the drive should be displayed.
Storage::disk('public')->directories();
```

**Comment by olcy** [comment]
The command return this : 
`Psy Shell v0.9.9 (PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 — cli) by Justin Hileman
>>> Storage::disk('public')->directories();
PHP Warning:  mkdir(): Invalid path in /var/www/sarp-front-end/vendor/league/flysystem/src/Adapter/Local.php on line 104
League/Flysystem/Exception with message 'Impossible to create the root directory "". '
>>>`

**Comment by alexusmai** [comment]
I think the problem is in the folder permissions...  you using storage folder - it mean you need to create a symbolic link(see higher), then you need to add folders permissions:

```
find /var/www/your_folder_here/storage/* -type d -exec chmod 775 {} \;
```

The user may not have access rights to these folders...

**Comment by olcy** [comment]
Thnk's for you're help @alexusmai !

The problem is solved, i have delete the symlink in /var/www/public/storage
and in /var/www/storage/app/storage

And i have tried to regenerate it with php artisan storage:link

You're package is awesome ! 👍

**Comment by yudhees** [comment]
@alexusmai  I have an issue when I upload my project in live server and opens file manager it give internal server error 500 but file manager works fine in localhost
