### ISSUE TITLE
include file-manager.js make information overwrite in debugbar 

### ISSUE THREAD

**Issue by shinnlu** [alexusmai/laravel-file-manager#55]
Laravel Version: 5.5
config/file-manager.php
`'middleware' => ['web','admin.auth'],`

i have install barryvdh/laravel-debugbar for debug, when i visit the page which include 'file-manager.js' will check the permission in middleware.

steps to reproduce issue:
when i visit the page, i can see there are many Queries in debugbar
![螢幕快照 2019-07-21 下午2 39 20](https://user-images.githubusercontent.com/570246/61587908-6b61f680-abc5-11e9-8ddf-be2efd38f7ac.png)
but in  milisecond, it refresh and only one query
![螢幕快照 2019-07-21 下午2 41 22](https://user-images.githubusercontent.com/570246/61587916-a401d000-abc5-11e9-9fb7-a32c659e2a60.png)

is it possible to run middleware check after i click on the 'Browser Server' and file manager show up.
![image](https://user-images.githubusercontent.com/570246/61588010-d5c76680-abc6-11e9-94b3-66ebe5e2f8da.png)

**Comment by alexusmai** [comment]
Hi.
File manager don't generate any requests to DB. Your middleware may create requests. And if you don't open the file manager it doesn't generate any requests..

**Comment by shinnlu** [comment]
> Hi.
> File manager don't generate any requests to DB. Your middleware may create requests. And if you don't open the file manager it doesn't generate any requests..

i found the problem after i read Installation guide again, it is not necessary to include file-manager.js to Integrated with CKEditor.

file-manager.js is use for show file manager to page directly.

it's my bad, thanks for your answer, and problem solved.
