### ISSUE TITLE
Select a file from mouse context menu not working

### ISSUE THREAD

**Issue by Fredericld** [alexusmai/laravel-file-manager#57]
Hi,

I really like the file manager so well done!

Slight issue though, selecting a file to insert in a text field does not work when I click on "select" in the mouse context menu. It just does nothing. But if I double-click on the file, then it works and the filename gets inserted in the input field.

```
<div class="form-group">
	<label for="fav_icon">Favicon</label> 
	<input aria-describedby="button-image" placeholder="Favicon" name="fav_icon" type="text" value="/files/My Images/universe-2742113_1280.jpg" id="fav_icon" class="form-control"> 
	<div class="input-group-append">
		<button type="button" id="button-image" class="btn btn-outline-secondary">Select</button>
	</div>
</div>


@push('scripts')

	<script>
	document.addEventListener("DOMContentLoaded", function() {

	  document.getElementById('button-image').addEventListener('click', (event) => {
	    event.preventDefault();

	    window.open('/file-manager/fm-button', 'fm', 'width=1400,height=800');
	  });
	});

	// set file link
	function fmSetLink($url) {
	  document.getElementById('fav_icon').value = $url;
	}
	</script>

@endpush

```
This was tested in Chrome and Firefox. It could be a mistake I made but the fact the double-click works makes me believe something is not right

Thanks

**Comment by alexusmai** [comment]
Hi, thank you, I found the problem and fixed it. In a new version will be changes..
