### ISSUE TITLE
Remember directory last opened from?

### ISSUE THREAD

**Issue by Thuongkim** [alexusmai/laravel-file-manager#58]
I open images folder and see all file inside but when i come back or copy and pate this link in new tab it just go to the default location and i dont know what file or folder i open before. Can it go to the directory what i last opened a file from ? (Thank you and Hope you reaply !)
![image](https://user-images.githubusercontent.com/41858767/62124400-4e7ba080-b2f4-11e9-961f-f26b3bd87f06.png)
![image](https://user-images.githubusercontent.com/41858767/62124633-eaa5a780-b2f4-11e9-9069-2ea74f909f31.png)

**Comment by alexusmai** [comment]
Hi,
No, the application can't save the folder that you opened before.
You are the second, who requested this feature. Maybe, I'll add this in a new version..
