### ISSUE TITLE
Можно ли в  блейд передавать корневую папку?

### ISSUE THREAD

**Issue by mttzzz** [alexusmai/laravel-file-manager#59]
Добрый день! Александр, спасибо большой за вашу разработку. У меня следующая задача. Есть сложная структура папок  с подпапками, мне нужно динамически отдавать нужную, чтобы она была корнем и выше подняться было нельзя. Посоветуйте пожалуйста варианты, если они возможны.

**Comment by MWStudio4** [comment]
Сам работаю над похожей задачей. Пока сделал вручную через конфиг ACL. Теперь думаю, как менять ACL динамически) То есть при установке флага 'aclHideFromFM' => true, пользователь будет видеть только свои папки. Но как сделать чтобы при добавлении пользователя, правился конфиг...

**Comment by MWStudio4** [comment]
Все получилось. Реализовал интерфейс ACL и написал свой класс. В конфиг поставил свой класс как реализатор ACL. 
Смотреть

 'aclRepository' => Alexusmai\LaravelFileManager\Services\ACLService\ConfigACLRepository::class,

**Comment by alexusmai** [comment]
День добрый, если все пользовательские папки находятся на одном уровне - например в папке users - лежат папки пользователей (users/user1, users/user2, users/userN...), тогда как в совете выше делаете.. в документации есть пример, именно такой реализации. Правда корневой папкой всегда будет папка users, но доступ у пользователя будет только к своей папке, и другие он видеть не будет (может и видеть, но изменять не выйдет - это можно настроить).
А вот если структура папок другая, то тут потребуется как-то динамически генерировать список дисков для самой Ларавел, а для ФМ динамические настройки есть.. там уже нужно будет получать нужный диск и ACl под него будет генерировать правила, такой вариант я не делал...
