### ISSUE TITLE
File: no extension error

### ISSUE THREAD

**Issue by beckj94** [alexusmai/laravel-file-manager#6]
I found out that if by some miracle the file has no extension the application throws this error and does not show the contents of the folder containing it:

`TypeError: Cannot read property 'toLowerCase' of undefined`

I did a workaround to this in the _file-manager.js_ file on the line 268 in the function `extensionToIcon()`:

```
if(t == '' || !t) {
    return "fa-file"
}
```

so now it doesn't throws the error and assigns the file a generic icon.

**Comment by alexusmai** [comment]
Thank you. Fixed.
