### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by IVoyt** [alexusmai/laravel-file-manager#61]
Is it possible to get relative path of selected file from both standalone and text-editor?

**Comment by alexusmai** [comment]
Hi, see the docs - [integration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md)

**Comment by IVoyt** [comment]
> Hi, see the docs - [integration](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/integration.md)

Thank you for your response.
Maybe I've missed something but I didn't see here any example how to return relative path of selected file.
```
// set file link
function fmSetLink($url) {
  document.getElementById('image_label').value = $url;
}
```
The function for standalone button returns absolute url, which I have to parse to get desired relative path. The question was how to get relative path "out-of-box" if it is possible.

**Comment by alexusmai** [comment]
Ok, I understood..
The returned link depends on your settings. 
See config/filesystems.php - disks array,

```
'url' => env('APP_URL').'/images',
```

Result - mysite.com/images/image.png

```
'url' => '/images',
```

Result - /images/image.png

**Comment by IVoyt** [comment]
So easy) I'm new to Laravel. Thanks a lot! =)

**Comment by Fredericld** [comment]
Thanks. all good!
