### ISSUE TITLE
Best way to handle multiple image sizes

### ISSUE THREAD

**Issue by newelement** [alexusmai/laravel-file-manager#66]
What would you recommend the best way to handle resizing image when uploading? For example having small, medium and large images. Should I have a listener on the event and resize at that point?

**Comment by alexusmai** [comment]
Hi,

I would use events, they exists for loading. [FilesUploaded](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)
If you need to make several different images, I would use queues. [Queues](https://laravel.com/docs/queues)

File uploaded -> Event -> Add a new task to the queue.

**Comment by vahidalvandi** [comment]
please show a simple
after upload , after rename , after delete ,after move ,... all size sync whit original image 

very thanks
