### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by Laussii078** [alexusmai/laravel-file-manager#67]
Hi,
A friendly reminder that Laravel 6.0 has been released but unfortunately when using this file manager it isn't possible to update to the newest version yet. Could you make it compatible with the latest release? Thanks in advance.

**Comment by alexusmai** [comment]
Laravel 6 support added, but not fully tested!
You need to install - String & Array Helpers Package

```
composer require laravel/helpers
```

**Comment by menkaff** [comment]
I install laravel helpers but  still composer can't install
`Problem 1
    - Conclusion: don't install alexusmai/laravel-file-manager v2.4.4
    - Conclusion: don't install alexusmai/laravel-file-manager v2.4.3
    - Conclusion: don't install alexusmai/laravel-file-manager v2.4.2
    - Conclusion: don't install alexusmai/laravel-file-manager v2.4.1
    - Conclusion: remove laravel/framework v6.1.0
    - Installation request for alexusmai/laravel-file-manager ^2.4 -> satisfiable by alexusmai/laravel-file-manager[v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4].
    - Conclusion: don't install laravel/framework v6.1.0
    - alexusmai/laravel-file-manager v2.4.0 requires laravel/framework 5.5.*|5.6.*|5.7.*|5.8.* -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.1.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.1.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.1.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.1.0].
    - Installation request for laravel/framework (locked at v6.1.0, required as ^6.0) -> satisfiable by laravel/framework[v6.1.0].
`

**Comment by menkaff** [comment]
Well i fixed it
First downgrade to laravel "6.0" then install this file manager successfully and then change laravel version in composer to "^6.0" and it just goes till "6.0.4"

**Comment by alexusmai** [comment]
Hi, thanks, I fixed the dependencies.
