### ISSUE TITLE
Proper ACL configuration for a project

### ISSUE THREAD

**Issue by Ainur777** [alexusmai/laravel-file-manager#70]
Привет, спасибо за пакет, выбирал из трех пакетов, но ваш мне показался наиболее интересным. Установил, настроил как положено, создал ACL и настроил.
В своем проекте хочу сделать следующее:
 ### **1) Показывать в списке дисков только те которые доступны пользователю.**
Пример: у пользователя есть группа '1',  и в filesystem 'office_1'
```
        'office_1' => [
            'driver' => 'local',
            'root' =>  storage_path('app/public/office_1'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'Office 1',
        ],
```
У другого пользователя группа 2, и в filesystem 'office_2'
```
        'office_2' => [
            'driver' => 'local',
            'root' =>  storage_path('app/public/office_2'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'Office 2',
        ],
```
И таких групп может быть много, как сделать отображение только той группы, которая задана пользователю?
![image](https://user-images.githubusercontent.com/43144793/65366277-27c65000-dc3b-11e9-8c0d-375d8a34f737.png)

### **2) Как настроить автоматический переход в директорию**
Я ознакомился с вашим пакетом и есть там в **file-manager**, **leftPath** который задает переход в директорию, а как сделать чтобы переходил в папку пользователя по логину.
Я создал:
```
        'private_folder_office_1' => [
            'driver' => 'local',
            'root' =>  storage_path('app/public/office_1/private_folder'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'Private folder',
        ],
```
В папке private_folder, хранятся папки пользователей по логину.
Как сделать автоматический переход? Ведь если я перейду, то отобразится только папка пользователя, необходимо будет перейти по нему.

### **ACL**
```
        $dir_user = \Auth::user()->id . '_' .\Auth::user()->login;
        $user_org_prefix = \Auth::user()->prefix_org;
        return [
            ['disk' => 'office_'.$user_off_prefix, 'path' => '*', 'access' => 1], //Группа пользователя
            ['disk' => 'private_folder', 'path' => '/', 'access' => 1],
            ['disk' => 'private_folder', 'path' => $dir_user, 'access' => 1],
            ['disk' => 'private_folder', 'path' => $dir_user.'/*', 'access' => 2],
        ];
```
### **Ошибки**
При загрузке файлов возникает ошибка:

> 500 - Undefined index: Private folder

При том если нажать несколько раз, то они все таки загружаются, как это?
В конфигурации настроил по типам загрузки файлов
`'allowFileTypes' => ['doc','docx','xls','xlsx','xlsb','pdf','zip','rar'],`

**Comment by Ainur777** [comment]
1 вопрос решил. Имхо изучать нужно лучше документацию к пакету. Кому интересно копайте в сторону класса ConfigRepository. В пакете все есть. Нужно только реализовать все методы этого класса.

**Comment by alexusmai** [comment]
Привет.
Если с первым вопросом разобрались, то думаю со вторым так же проблем не возникло. В своем Configrepository в методе getLeftPath() отдаете путь к папке которую нужно открыть

```
public function getLeftPath(): ?string
    {
        return \Auth::user()->name; // например путь будет - admin (для пользователя с именем admin)

        // return 'folder/users/'.\Auth::user()->name; // folder/users/admin

       // return '/'.\Auth::user()->name; // так работать не будет, '/' ставить впереди не нужно!
    }
```

Если конфигурация папок сложнее тогда нужно писать свою логику которая будет генерировать нужный путь.

Насчет ошибки при загрузке файлов - не могу повторить.. 
Единственный момент сейчас нашел при загрузке - это если есть два типа файлов и один из них нельзя загружать - то будет загружен разрешенный файл, а в ответ прийде сообщение, что не все файлы загружены.. но не обновиться список файлов.. и тот что загружен не будет в списке, нужно в ручную нажать кнопку обновить..

По поводу поиска и других функций - пока нет времени.. если будет то посмотрю..
