### ISSUE TITLE
Responsive frontend - Edit view files

### ISSUE THREAD

**Issue by daugaard47** [alexusmai/laravel-file-manager#71]
I was wondering. Is there a quick way to make the front-end responsive so it will be accessible on mobile devices? Using with S3 and would like a quick way to share documents and upload images via my phone. 

I tried messing around with the Vue front-end, but honestly was unclear on how to add it to the backend? Is the backend-laravel-file-manager and the front-end - vue-file-manager supposed to be decoupled? 

Lastly do you plan on creating more features? I would like to put in the request of a Search function and select multiple files by "Select all" or "shift + left-click"

Thank you for the time and effort that went into this. Much appreciated.

**Comment by alexusmai** [comment]
Hi, thank you.
Yes, the interface is not optimized for mobile devices.
laravel-file-manager - it's an API for your laravel storages,
vue-laravel-file-manager - it's only frontend, they cannot be separated.

Multiple select - Ctrl + left-click

More features may be in the future ... but now I do not have time.
