### ISSUE TITLE
Folder not showing 

### ISSUE THREAD

**Issue by D-buenaflor** [alexusmai/laravel-file-manager#72]
Hi downloaded this package and apply it to my local laravel 5.4 .... I followed the installation and configuration procedures but when i load the page i cannot see any folders in my public folder.

![image](https://user-images.githubusercontent.com/42760558/65576655-f3d58c80-dfa4-11e9-8054-f798e35657f3.png)

and when viewing the initialization (sitename/file-manager/initialize) i see the my configs.

![image](https://user-images.githubusercontent.com/42760558/65576829-40b96300-dfa5-11e9-8b37-de7f30830bdc.png)

what should i do???

**Comment by alexusmai** [comment]
Hi, you need to use Laravel 5.5 or higher.
