### ISSUE TITLE
500 internal erro ("Object of class Closure could not be converted to string")

### ISSUE THREAD

**Issue by macalimosa** [alexusmai/laravel-file-manager#73]
i've tried to install this plugin from laravel 5.4 and i got this error. btw im using default configuration. 
![image](https://user-images.githubusercontent.com/17537603/65577319-2633b980-dfa6-11e9-80f7-7a7fceeec5de.png)

**Comment by alexusmai** [comment]
Hi, you need to use Laravel 5.5 or higher.
