### ISSUE TITLE
file manger can't show images 

### ISSUE THREAD

**Issue by kazemimorteza68** [alexusmai/laravel-file-manager#75]
file  manager upload images properly but can't show images.

![Screenshot from 2019-09-30 13-08-05](https://user-images.githubusercontent.com/7469558/65867486-61a5fd80-e383-11e9-94c9-35ce4dbfe358.png)

my laravel version is 6.0.4

all files and directories permission is 777 .
Request URL:http://127.0.0.1:8000/file-manager/preview?disk=public&path=2283900.jpg&v=1569834275

Status code:
500 Internal Server Error
![Screenshot from 2019-09-30 13-18-50](https://user-images.githubusercontent.com/7469558/65868310-e0e80100-e384-11e9-8349-e719151c95ca.png)

**Comment by alexusmai** [comment]
Hi, 
Maybe you forgot to create a symbolic link ? -  [laravel docs](https://laravel.com/docs/filesystem#the-public-disk)
