### ISSUE TITLE
Progressive and optimized Image

### ISSUE THREAD

**Issue by nasirkhan** [alexusmai/laravel-file-manager#76]
While uploading the images via this filemanager, is there any to make the image progressive and optimized jpg?

**Comment by alexusmai** [comment]
Hi.
The File manager doesn't make any operations with files after uploading, but you can use [events](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)

**Comment by nasirkhan** [comment]
thanks, do you have any sample code of using the events? or can you please mention which event should i listen?

**Comment by nasirkhan** [comment]
> thanks, do you have any sample code of using the events? or can you please mention which event should i listen?

I asked a question on the previous comment, i am not sure why you closed the issue without answering or mentioning anything!

**Comment by alexusmai** [comment]
Hi,
You can find sample in the documentation  - [Events - FilesUploaded](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)

Please see my previous message, you can see this link.
