### ISSUE TITLE
Namespace dependency

### ISSUE THREAD

**Issue by murcoder** [alexusmai/laravel-file-manager#8]
Hi there!

The `FileManagerController` extends the **`App\Http\Controllers\Controller`**. This will be a problem, if the Laravel application namespace has changed e.g. in `MyProject\...`
You should prevent a dependency to the user's application by
**`use Illuminate\Routing\Controller;`**

**Comment by alexusmai** [comment]
Hi, thanks, I'll think about it. I am working on a new version.
