### ISSUE TITLE
интеграция с laravel-admin

### ISSUE THREAD

**Issue by phpner** [alexusmai/laravel-file-manager#80]
Добрый день! 
Пытаюсь интегрировать с админкой https://laravel-admin.org/docs/#/

когда я прописываю в файле file-manager.php : 
'middleware' => ['web','admin']

пишет - "Доступ запрещен"...

Дело в том, что эта админка работает через PREFIX "admin"  и когда я меняю в файле admin.php, настройки данной админ панели, 
строку  'prefix' => env('ADMIN_ROUTE_PREFIX', 'admin'), 
на  'prefix' => env('ADMIN_ROUTE_PREFIX', '')

все прекрасно работает ! Но админ панель работает без префикса "admin"   чего бы не хотелось....

Есть возможность запустить  laravel-file-manager с PREFIX admin ?

вроде бы перепробовал много разных вариантов, но все как-то не работает...

**Comment by alexusmai** [comment]
День добрый.

Есть два варианта:

1. Самому собирать фронт для файлового менеджера - [vue-laravel-file-manager](https://github.com/alexusmai/vue-laravel-file-manager) - там есть несколько вариантов как изменить baseURL,

2. Написать свой middleware - в котором делать нужные проверки - например проверять авторизован ли пользователь и есть ли у него права(роль) для использования файлового менеджера.

**Comment by phpner** [comment]
Спасибо за ответ! Написал свой middleware  и все заработало!
