### ISSUE TITLE
Error not instantiable

### ISSUE THREAD

**Issue by Cristiano1103** [alexusmai/laravel-file-manager#81]
In Container.php line 979:
                                                                               
  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepositor  
  y] is not instantiable.

**Comment by hakhagmon** [comment]
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 979:

  Target [Alexusmai\LaravelFileManager\Services\ConfigService\ConfigRepository] is not instantiable.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

**Comment by alexusmai** [comment]
Hi, I can't to repeat this problem. I checked new installation on Laravel 5.7 and Laravel 6.3

```
Using version ^2.4 for alexusmai/laravel-file-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-util (v1.12.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.12.0): Loading from cache
  - Installing jeremeamia/superclosure (2.4.0): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing intervention/image (2.5.0): Loading from cache
  - Installing intervention/imagecache (2.4.0): Loading from cache
  - Installing alexusmai/laravel-file-manager (v2.4.6): Loading from cache
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: alexusmai/laravel-file-manager
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
```

But, If you are upgrading the package - try to remove the config file (config/file-manager.php) before updating.

**Comment by hakhagmon** [comment]
> Hi, I can't to repeat this problem. I checked new installation on Laravel 5.7 and Laravel 6.3

Laravel 6.3, Windows Server 2016, OpenServer

**Comment by alexusmai** [comment]
I think problem isn't in the OS, but you can try to use Homestead.

Are you making fresh installation or updating the package? If updating - show config file (config/file-manager.php)

**Comment by hakhagmon** [comment]
> I think problem isn't in the OS, but you can try to use Homestead.
> 
> Are you making fresh installation or updating the package? If updating - show config file (config/file-manager.php)

С нуля ставил

**Comment by lkloon123** [comment]
this is due to previous `config/file-manager.php` doesn't have `configRepository` field, make sure u update the config file and delete `boostrap/cache/config.php` if exist
