### ISSUE TITLE
  Call to a member function getMiddleware() on string

### ISSUE THREAD

**Issue by bilalmaqsood** [alexusmai/laravel-file-manager#82]
We are using this package it work well on local machine , but on the server it shows the following error, 
In routes.php line 8:

 ` $middleware = $config->getMiddleware();`
  `Call to a member function getMiddleware() on string`
I did try all the laravel commands to clear config, clear routes and clears cache, dump-autoload but nothing seems to be working for me,
we have PHP 7.2.22 , OS ubuntu18 on server

**Comment by nivanmorgan** [comment]
@alexusmai can you help us fix this issue. we are having problems installing the package when we require the composer package we get 

Call to a member function getMiddleware() on string.

**Comment by alexusmai** [comment]
Hi, I don't know where is the problem. But you can try to full reinstallation of package, maybe on local machine you was using old version, but when you moved to the server you installed latest version and configuration file you didn't update.

```
php artisan vendor:publish --tag=fm-config --force
```

**Comment by Alistair-zhong** [comment]
change the code in routes.php
before
`$config = resolve(ConfigRepository::class);`
after
`$config = app(ConfigRepository::class);`

**Comment by DevNull-IR** [comment]
Hello, I have this error too

500 - Call to a member function send() on string
The error is related to the file:
`path/public/index.php`
and the send method in the file

**Comment by DevNull-IR** [comment]
> change the code in routes.php before `$config = resolve(ConfigRepository::class);` after `$config = app(ConfigRepository::class);`

Thank you for helping me
@Alistair-zhong
