### ISSUE TITLE
Hiden Folder Not Activity

### ISSUE THREAD

**Issue by tuantrinitri** [alexusmai/laravel-file-manager#83]
Hello sir.
I have some problems and need your help!
I have a module and when I click on more pictures, only the module's folder is displayed and all other folders are hidden.
Do you have a solution?
Sorry about my English. Thanks

**Comment by alexusmai** [comment]
Hello, it is not clear what is needed. You can use ACLs to hide folders - [docs](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/acl.md#acl)
