### ISSUE TITLE
possibility to hide or show hidden files

### ISSUE THREAD

**Issue by Haititi** [alexusmai/laravel-file-manager#88]
Hi!
First of all, well done for your awesome work! Your solution is working really well!

I would like to ask you if there is any way to implement an option to hide or show any hidden files/directories (with name starting with a dot "." ) ?

Thanks for your help!

**Comment by alexusmai** [comment]
Hi, thank you.

Perhaps in new versions I'll implement this functionality.

**Comment by Haititi** [comment]
I would be really thankful!
Hope you do it soon haha 😊

**Comment by alexusmai** [comment]
It's done! You can test a new version [2.4.7](https://github.com/alexusmai/laravel-file-manager/releases/tag/v2.4.7)

**Comment by Haititi** [comment]
awesome!! thank you very much!

now i have a last problem to notify you with, but i will create a new issue for that :)
thank you!
