### ISSUE TITLE
To show Sub folders and files in left side tree view as Indented

### ISSUE THREAD

**Issue by anilone** [alexusmai/laravel-file-manager#90]
Is there  any way to show the sub folders like the way that in your documentation GiF ! 
In my tree view, the files/folders list at same level(not indented view)

SS from your GIF shown below

![doc image](https://user-images.githubusercontent.com/700857/68468502-2af2bb00-023e-11ea-9583-20330de10e2e.jpg)

SS form my project shown below

![file manager](https://user-images.githubusercontent.com/700857/68468327-cdf70500-023d-11ea-8737-bc47839944e3.png)

**Comment by alexusmai** [comment]
Maybe some your styles overwrite FM styles. Are you trying to use FM on a simple page without any css files except bootstrap, fontawesome and FM styles ?

**Comment by anilone** [comment]
Hi,
Issue solved by removing some of my custom styles and bootstrap links.

![indended](https://user-images.githubusercontent.com/700857/68760811-b8684d80-0638-11ea-8e3b-e09fdc35ff4a.png)

Thanks !
