### ISSUE TITLE
Not show file and folder

### ISSUE THREAD

**Issue by TuxCod** [alexusmai/laravel-file-manager#91]
Hello,

I have a problem:
always displays data from the folder "/storage/app/" I can not get inside.
If you create a file or folder, it is created in the right place
"/storage/app/public/"
My config is standard

`'diskList'  => ['public'],`

```

'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

    ],
```

<img width="673" alt="Снимок экрана 2019-11-14 в 12 17 42" src="https://user-images.githubusercontent.com/230804/68832384-fae26680-06da-11ea-9cef-20bebcb12768.png">

**Comment by alexusmai** [comment]
Hi, this is strange, I can't repeat the problem. Were you trying to use "local" disk? He is working?

**Comment by TuxCod** [comment]
> Hi, this is strange, I can't repeat the problem. Were you trying to use "local" disk? He is working?

i use this on vds server

`'diskList'  => ['local'],`
this not work - works similarly

**Comment by TuxCod** [comment]
I change config

filesystems.php:
```
'images' => [
            'driver' => 'local',
            'root' => public_path('img'),
            'url' => env('APP_URL').'/img',
        ],
```

file-manager.php:
`'diskList' => ['images', 'public'],`

I still see the contents as before
<img width="876" alt="Снимок экрана 2019-11-14 в 17 21 48" src="https://user-images.githubusercontent.com/230804/68853036-43ae1580-0703-11ea-8fff-e4163ffbc0fc.png">

**Comment by alexusmai** [comment]
What does this function return? - Storage::disk('public')->listContents();
I didn’t understand - is the 'images' disk showing the same result? as 'puplic' disk?
