### ISSUE TITLE
ckeditor image path getting preceded by `/` causing incorrect path

### ISSUE THREAD

**Issue by devsrv** [alexusmai/laravel-file-manager#93]
if the `APP_URL` is set to `http://domain.com/` i.e an url with `/` at the end then the image path returned by the file manager for ckeditor is generating a path that is preceded by `/`

![image](https://user-images.githubusercontent.com/26733312/69142729-69fdf780-0aed-11ea-9d12-1b05c7f47b33.png)

![image](https://user-images.githubusercontent.com/26733312/69142815-9ade2c80-0aed-11ea-95bd-bc283ab9d87e.png)

**Comment by alexusmai** [comment]
Hi,

You can use this variable without slash, or in the config file - config/filesystems.php edit your disks settings, example:

```
'public' => [
            'driver' => 'local',
            'root' => public_path('files'),
            'url' =>env('APP_URL'). '/files', // <--- edit this line, remove slash
            'visibility' => 'public',
        ],


'public' => [
            'driver' => 'local',
            'root' => public_path('files'),
            'url' =>env('APP_URL'). 'files', // result
            'visibility' => 'public',
        ],
```

**Comment by devsrv** [comment]
I get it 👍
