### ISSUE TITLE
Middleware configuration OR routes export

### ISSUE THREAD

**Issue by iSpeeX** [alexusmai/laravel-file-manager#94]
Hi everyone,

I'm using this file manager for my project and while it's a must have to get a simple fm in a Laravel app, I'm facing a lot of problems to enable middleware configuration.
The documentation is quite short concerning the middleware and I hope that some of you will have some answers or ideas.

The context is a Laravel app with an already running Middleware (_working well_) for all pages except the file manager. 
I tried to disabled the ACL and change the "web" middleware by my own, then I tried to change the route config file of this file manager(_routes.php in vendor folder_) and also to export theses routes in my "web.php" file (_where my middleware group for routes is located_).

But in any way I'm getting the **"401 unauthenticated"** error.

**Am I forgetting something ? Do any of you know a way to make this work ?**

I really hope that some of you will be able to help me and in this case : thank you very much !

Best regards

**Comment by alexusmai** [comment]
Hi,

Middleware connecting in a config file - config/file-manager.php 

example:

```
'middleware' => ['web', 'your-middleware-name'],
```

'web' - it's a standart laravel middleware for web routes (These routes all receive session state, CSRF protection, etc.)

Need more information.. show your config file, show your middleware that you want to use with FM

**Comment by iSpeeX** [comment]
I have to say thank you, I just replaced 'web' by my own middleware... now it's back on track !
