### ISSUE TITLE
feature request: move file to other folder

### ISSUE THREAD

**Issue by VincentVanWijk** [alexusmai/laravel-file-manager#95]
Hi, 
is it possible to create move file to folder functionality? Maybe with an MoveEvent that shows oldPath and newPath, so we can update database to newPath.

Else, is it Possible to have a oldPath and newPath variable in the LaravelFileManager\Events\Paste?
What we have now is already kinda that way, but it is only the new path, and the oldpath is in the files array, including the file and extension, if this was the same format (maybe both full path), find and replace in db wolud be easier.
![image](https://user-images.githubusercontent.com/10919865/69415513-0d7d2100-0d15-11ea-9578-3fb4d04b2a6b.png)

thanks in advance!
Vincent

**Comment by alexusmai** [comment]
Hi, 
If I understood you correctly, you can get all what you need using "Paste" event.

Example for files

```
$newPath = $event->path() ? $event->path().'/' : '';

$files = array_map(function ($item) use($newPath) {
    return [
        'oldPath' => $item,
        'newPath' => $newPath.basename($item)
    ];
}, $event->clipboard()['files']);
```

**Comment by VincentVanWijk** [comment]
Ah thanks, this is indeed what i was looking for!
