### ISSUE TITLE
SummerNote get file name

### ISSUE THREAD

**Issue by gnrbrhm** [alexusmai/laravel-file-manager#96]
Hi everyone.  I used summernote.blade in the vendor file

I want to get the name of the uploaded file when the file upload is complete.

at the same time 

I need to update the file name to process for  the database 

```

`<script>
    document.addEventListener('DOMContentLoaded', function() {
        // set fm height
        document.getElementById('fm-main-block').setAttribute('style', 'height:' + window.innerHeight + 'px');

        // Add callback to file manager
        fm.$store.commit('fm/setFileCallBack', function(fileUrl) {
            window.opener.fmSetLink(fileUrl);
            window.close();
        });
    });
</script>`
```
I think I can send a http request with jquery ajax on the above javascript code, but I don't understand the structure.

thanks in advance for help

**Comment by alexusmai** [comment]
Hi.

You'll get all information about uploaded files using events - [FilesUploaded](https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#filesuploaded)
