### ISSUE TITLE
Path Not Found After Create Directory On Cloud Storage

### ISSUE THREAD

**Issue by gdevilbat** [alexusmai/laravel-file-manager#97]
Hi, There,

after create directory on cloud s3 storage, there is an error like path not found. This is because on cloud storage cant listing empty directory. I found a solution.

Can you put, .gitattributes or any 0 bytes file on directory, after creating direcrtory ?

**Comment by alexusmai** [comment]
Hi, 
I think you use an old version of FileManager, because this error fixed in new versions

**Comment by gdevilbat** [comment]
I'm using the newest version, but still in error

![image](https://user-images.githubusercontent.com/13155181/69828357-34c07a80-124e-11ea-8d7c-037ea57089b4.png)

![image](https://user-images.githubusercontent.com/13155181/69828473-941e8a80-124e-11ea-94c6-675976963b7d.png)

i change manually on vendor file to make it work 
Storage::disk($disk)->makeDirectory($directoryName) ---------> Storage::disk($disk)->put($directoryName.'/'.'.gitattributes', '');

**Comment by alexusmai** [comment]
I can't repeat an error..
I created a new s3 storage - and I can create folders and select them without any errors.(empty folders too)

![FireShot Capture 030 - Laravel - lfm loc](https://user-images.githubusercontent.com/7473505/69846012-b2eb4400-1283-11ea-8bc3-3e98dd300aad.png)

**Comment by gdevilbat** [comment]
Hi, Mr. Alex,

I'm using minio as storage object service, T_T
https://min.io/

**Comment by alexusmai** [comment]
I don't know anything about minio, but i know how to create ".gitatributes" file for new folder, without changing vendor files.

You can use (Events)[https://github.com/alexusmai/laravel-file-manager/blob/master/docs/events.md#directorycreated]

code example:

```
// directory created
\Event::listen('Alexusmai\LaravelFileManager\Events\DirectoryCreated',
    function ($event) {
        $path = $event->path() ? $event->path().'/' : '';

        // create new file
        \Storage::disk($event->disk())->put($path.$event->name().'/.gitattributes', '');
    }
);
```

**Comment by gdevilbat** [comment]
i've tried this before.

But it returning error path not found, before Event Triggered.

$createDirectoryResponse = $this->fm->createDirectory(
            $request->input('disk'),
            $request->input('path'),
            $request->input('name')
        );----->>>>>>>>>>>>Return Error Path Not Found Before Event Triggered

        if ($createDirectoryResponse['result']['status'] === 'success') {
            event(new DirectoryCreated($request));
        }

**Comment by alexusmai** [comment]
Does this function return an error?

```
Storage::disk($disk)->getMetadata($emptyPath);
```

What adapter (Flysystem) do you use for minio?
