### ISSUE TITLE
404 (not found) - domain with subdirector

### ISSUE THREAD

**Issue by mbogunia** [alexusmai/laravel-file-manager#99]
I have a domain with a sub director, and I can't change it.
example.com/**site**/

File Manager return the error "Not Found".

404 is the answer to the request _example.com/file-manager/initialize._

Where can I change this address to
example.com/**site**/file-manager/initialize ?

**Comment by alexusmai** [comment]
Hi,
You can change base URL, but you'll need to use (vue-laravel-file-manager)[https://github.com/alexusmai/vue-laravel-file-manager], not a pre-compiled js

**Comment by mbogunia** [comment]
Have you maybe files with example how use it (Laravel 6.x).
I try to run this, but i don't know Vue.

**Comment by alexusmai** [comment]
You need at least minimal knowledge of Vue to use it.
Laravel MIX - [doc](https://laravel.com/docs/mix)
Package [doc](https://github.com/alexusmai/vue-laravel-file-manager)

**Comment by ArashYounesi** [comment]
I did it by editing file `file-manager.js`.

**Comment by deepakjhapoly** [comment]
![image](https://user-images.githubusercontent.com/54061827/171098382-6c160796-5bc0-417d-9afc-149cdcfdd254.png)
Ajax url not contain base url on calling.
 http://localhost/file-manager/initialize
